// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sqrt_fix_sqrt_fixed_32_16_s (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] x;
output  [23:0] ap_return;
input   ap_ce;

reg[23:0] ap_return;

reg   [31:0] x_read_reg_3603;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] x_read_reg_3603_pp0_iter1_reg;
reg   [31:0] x_read_reg_3603_pp0_iter2_reg;
reg   [31:0] x_read_reg_3603_pp0_iter3_reg;
reg   [31:0] x_read_reg_3603_pp0_iter4_reg;
reg   [31:0] x_read_reg_3603_pp0_iter5_reg;
reg   [31:0] x_read_reg_3603_pp0_iter6_reg;
wire   [15:0] trunc_ln731_fu_302_p1;
reg   [15:0] trunc_ln731_reg_3608;
reg   [15:0] trunc_ln731_reg_3608_pp0_iter1_reg;
wire   [18:0] x_l_I_V_74_fu_508_p3;
reg   [18:0] x_l_I_V_74_reg_3613;
wire   [7:0] res_I_V_18_fu_516_p3;
reg   [7:0] res_I_V_18_reg_3619;
wire   [0:0] icmp_ln489_3_fu_556_p2;
reg   [0:0] icmp_ln489_3_reg_3625;
wire   [5:0] sub_ln248_2_fu_562_p2;
reg   [5:0] sub_ln248_2_reg_3631;
wire   [0:0] icmp_ln318_1_fu_578_p2;
reg   [0:0] icmp_ln318_1_reg_3636;
reg   [0:0] icmp_ln318_1_reg_3636_pp0_iter1_reg;
wire   [7:0] res_I_V_22_fu_853_p3;
reg   [7:0] res_I_V_22_reg_3642;
wire   [0:0] icmp_ln489_7_fu_877_p2;
reg   [0:0] icmp_ln489_7_reg_3648;
wire   [18:0] x_l_I_V_79_fu_901_p3;
reg   [18:0] x_l_I_V_79_reg_3653;
wire   [18:0] x_l_I_V_17_fu_909_p2;
reg   [18:0] x_l_I_V_17_reg_3661;
wire   [7:0] res_I_V_fu_931_p3;
reg   [7:0] res_I_V_reg_3666;
reg   [7:0] res_I_V_reg_3666_pp0_iter3_reg;
reg   [7:0] res_I_V_reg_3666_pp0_iter4_reg;
reg   [7:0] res_I_V_reg_3666_pp0_iter5_reg;
reg   [7:0] res_I_V_reg_3666_pp0_iter6_reg;
wire   [16:0] res_FH_V_34_fu_1134_p3;
reg   [16:0] res_FH_V_34_reg_3681;
wire   [0:0] and_ln318_3_fu_1260_p2;
reg   [0:0] and_ln318_3_reg_3687;
wire   [16:0] x_l_FH_V_30_fu_1266_p3;
reg   [16:0] x_l_FH_V_30_reg_3692;
wire   [18:0] x_l_I_V_85_fu_1274_p3;
reg   [18:0] x_l_I_V_85_reg_3699;
wire   [2:0] trunc_ln104_2_fu_1282_p1;
reg   [2:0] trunc_ln104_2_reg_3708;
reg   [4:0] tmp_16_reg_3713;
wire   [3:0] trunc_ln104_3_fu_1296_p1;
reg   [3:0] trunc_ln104_3_reg_3718;
reg   [3:0] tmp_17_reg_3723;
wire   [4:0] trunc_ln104_4_fu_1310_p1;
reg   [4:0] trunc_ln104_4_reg_3728;
reg   [2:0] tmp_18_reg_3733;
reg   [2:0] tmp_18_reg_3733_pp0_iter3_reg;
wire   [5:0] trunc_ln104_5_fu_1324_p1;
reg   [5:0] trunc_ln104_5_reg_3738;
reg   [5:0] trunc_ln104_5_reg_3738_pp0_iter3_reg;
reg   [1:0] tmp_19_reg_3743;
reg   [1:0] tmp_19_reg_3743_pp0_iter3_reg;
wire   [6:0] trunc_ln104_6_fu_1338_p1;
reg   [6:0] trunc_ln104_6_reg_3748;
reg   [6:0] trunc_ln104_6_reg_3748_pp0_iter3_reg;
reg   [0:0] tmp_45_reg_3753;
reg   [0:0] tmp_45_reg_3753_pp0_iter3_reg;
wire   [16:0] res_FH_V_37_fu_1585_p3;
reg   [16:0] res_FH_V_37_reg_3758;
wire   [16:0] x_l_FH_V_34_fu_1593_p3;
reg   [16:0] x_l_FH_V_34_reg_3764;
wire   [18:0] x_l_I_V_89_fu_1601_p3;
reg   [18:0] x_l_I_V_89_reg_3770;
wire   [16:0] mul_FH_V_4_fu_1619_p4;
reg   [16:0] mul_FH_V_4_reg_3778;
wire   [0:0] icmp_ln318_19_fu_1628_p2;
reg   [0:0] icmp_ln318_19_reg_3783;
wire   [18:0] x_l_I_V_36_fu_1634_p2;
reg   [18:0] x_l_I_V_36_reg_3789;
wire   [16:0] res_FH_V_39_fu_1825_p3;
reg   [16:0] res_FH_V_39_reg_3794;
wire   [0:0] and_ln318_8_fu_1935_p2;
reg   [0:0] and_ln318_8_reg_3800;
wire   [16:0] x_l_FH_V_40_fu_1941_p3;
reg   [16:0] x_l_FH_V_40_reg_3805;
wire   [18:0] x_l_I_V_95_fu_1949_p3;
reg   [18:0] x_l_I_V_95_reg_3813;
wire   [16:0] res_FH_V_41_fu_2255_p3;
reg   [16:0] res_FH_V_41_reg_3822;
wire   [0:0] and_ln318_12_fu_2436_p2;
reg   [0:0] and_ln318_12_reg_3828;
wire   [16:0] x_l_FL_V_17_fu_2442_p3;
reg   [16:0] x_l_FL_V_17_reg_3833;
wire   [16:0] x_l_FH_V_46_fu_2450_p3;
reg   [16:0] x_l_FH_V_46_reg_3840;
wire   [18:0] x_l_I_V_101_fu_2458_p3;
reg   [18:0] x_l_I_V_101_reg_3849;
wire   [16:0] res_FH_V_44_fu_2831_p3;
reg   [16:0] res_FH_V_44_reg_3857;
wire   [0:0] and_ln318_18_fu_3012_p2;
reg   [0:0] and_ln318_18_reg_3863;
wire   [16:0] x_l_FL_V_20_fu_3018_p3;
reg   [16:0] x_l_FL_V_20_reg_3868;
wire   [16:0] x_l_FH_V_52_fu_3026_p3;
reg   [16:0] x_l_FH_V_52_reg_3875;
wire   [18:0] x_l_I_V_107_fu_3034_p3;
reg   [18:0] x_l_I_V_107_reg_3884;
wire    ap_block_pp0_stage0;
wire   [15:0] trunc_ln_fu_288_p4;
wire  signed [1:0] tmp_fu_306_p4;
wire  signed [2:0] sext_ln640_fu_316_p1;
wire   [18:0] zext_ln708_fu_298_p1;
wire   [2:0] add_ln248_fu_326_p2;
wire   [0:0] icmp_ln489_fu_320_p2;
wire   [18:0] p_Result_43_fu_332_p5;
wire   [7:0] res_I_V_16_fu_352_p3;
wire   [1:0] p_Result_s_38_fu_360_p4;
wire   [18:0] x_l_I_V_72_fu_344_p3;
wire   [2:0] tmp_1_fu_370_p3;
wire   [3:0] p_Result_1_fu_378_p4;
wire   [3:0] zext_ln489_fu_388_p1;
wire   [3:0] sub_ln248_fu_398_p2;
wire   [0:0] icmp_ln489_1_fu_392_p2;
wire   [18:0] p_Result_44_fu_404_p5;
wire   [7:0] p_Result_45_fu_416_p4;
wire   [7:0] res_I_V_17_fu_434_p3;
wire   [2:0] p_Result_4_fu_442_p4;
wire   [18:0] x_l_I_V_73_fu_426_p3;
wire   [3:0] tmp_2_fu_452_p3;
wire   [4:0] p_Result_5_fu_460_p4;
wire   [4:0] zext_ln489_1_fu_470_p1;
wire   [4:0] sub_ln248_1_fu_480_p2;
wire   [0:0] icmp_ln489_2_fu_474_p2;
wire   [18:0] p_Result_46_fu_486_p5;
wire   [7:0] p_Result_47_fu_498_p4;
wire   [3:0] p_Result_8_fu_524_p4;
wire   [4:0] tmp_3_fu_534_p3;
wire   [5:0] p_Result_9_fu_542_p4;
wire   [5:0] zext_ln489_2_fu_552_p1;
wire   [1:0] tmp_38_fu_568_p4;
wire   [18:0] p_Result_48_fu_584_p5;
wire   [7:0] p_Result_49_fu_594_p4;
wire   [7:0] res_I_V_19_fu_609_p3;
wire   [4:0] p_Result_10_fu_615_p4;
wire   [18:0] x_l_I_V_75_fu_603_p3;
wire   [5:0] tmp_4_fu_625_p3;
wire   [6:0] p_Result_11_fu_633_p4;
wire   [6:0] zext_ln489_3_fu_643_p1;
wire   [6:0] sub_ln248_3_fu_653_p2;
wire   [0:0] icmp_ln489_4_fu_647_p2;
wire   [18:0] p_Result_50_fu_659_p5;
wire   [7:0] p_Result_51_fu_671_p4;
wire   [7:0] res_I_V_20_fu_689_p3;
wire   [5:0] p_Result_13_fu_697_p4;
wire   [18:0] x_l_I_V_76_fu_681_p3;
wire   [6:0] tmp_5_fu_707_p3;
wire   [7:0] p_Result_14_fu_715_p4;
wire   [7:0] zext_ln489_4_fu_725_p1;
wire   [7:0] sub_ln248_4_fu_735_p2;
wire   [0:0] icmp_ln489_5_fu_729_p2;
wire   [18:0] p_Result_52_fu_741_p5;
wire   [7:0] p_Result_53_fu_753_p4;
wire   [7:0] res_I_V_21_fu_771_p3;
wire   [6:0] p_Result_16_fu_779_p4;
wire   [18:0] x_l_I_V_77_fu_763_p3;
wire   [7:0] tmp_6_fu_789_p3;
wire   [8:0] p_Result_17_fu_797_p4;
wire   [8:0] zext_ln489_5_fu_807_p1;
wire   [8:0] sub_ln248_5_fu_817_p2;
wire   [0:0] icmp_ln489_6_fu_811_p2;
wire   [18:0] p_Result_54_fu_823_p5;
wire   [7:0] p_Result_55_fu_835_p4;
wire   [18:0] x_l_I_V_78_fu_845_p3;
wire   [8:0] tmp_8_fu_861_p3;
wire   [9:0] trunc_ln640_fu_869_p1;
wire   [9:0] zext_ln489_6_fu_873_p1;
wire   [9:0] sub_ln248_6_fu_883_p2;
wire   [18:0] p_Result_56_fu_889_p5;
wire   [7:0] p_Result_57_fu_922_p4;
wire   [16:0] trunc_ln2_fu_937_p3;
wire   [18:0] zext_ln318_fu_945_p1;
wire   [0:0] icmp_ln318_fu_949_p2;
wire   [18:0] x_l_I_V_18_fu_959_p3;
wire   [16:0] x_l_FH_V_fu_915_p3;
wire   [0:0] icmp_ln1494_fu_976_p2;
wire   [0:0] or_ln318_fu_954_p2;
wire   [0:0] xor_ln1494_fu_981_p2;
wire   [0:0] and_ln318_1_fu_987_p2;
wire   [16:0] x_l_FH_V_26_fu_970_p2;
wire   [18:0] x_l_I_V_80_fu_964_p2;
wire   [16:0] res_FH_V_33_fu_993_p3;
wire   [0:0] trunc_ln104_fu_1026_p1;
wire   [1:0] p_Result_20_fu_1016_p4;
wire   [6:0] tmp_14_fu_1040_p4;
wire   [16:0] trunc_ln318_1_fu_1050_p3;
wire   [18:0] x_l_I_V_81_fu_1009_p3;
wire   [18:0] zext_ln318_1_fu_1058_p1;
wire   [16:0] p_Val2_23_fu_1001_p3;
wire   [16:0] mul_FH_V_fu_1030_p4;
wire   [0:0] icmp_ln318_2_fu_1062_p2;
wire   [0:0] icmp_ln318_3_fu_1068_p2;
wire   [18:0] x_l_I_V_fu_1080_p2;
wire   [18:0] x_l_I_V_21_fu_1086_p3;
wire   [0:0] icmp_ln1494_1_fu_1116_p2;
wire   [0:0] or_ln318_1_fu_1074_p2;
wire   [0:0] xor_ln1494_1_fu_1122_p2;
wire   [0:0] and_ln318_2_fu_1128_p2;
wire   [16:0] p_Result_58_fu_1106_p4;
wire   [16:0] x_l_FH_V_27_fu_1100_p2;
wire   [18:0] x_l_I_V_82_fu_1094_p2;
wire   [1:0] trunc_ln104_1_fu_1168_p1;
wire   [2:0] p_Result_21_fu_1158_p4;
wire   [5:0] tmp_15_fu_1182_p4;
wire   [16:0] trunc_ln318_2_fu_1192_p3;
wire   [18:0] x_l_I_V_83_fu_1150_p3;
wire   [18:0] zext_ln318_2_fu_1200_p1;
wire   [16:0] x_l_FH_V_28_fu_1142_p3;
wire   [16:0] mul_FH_V_1_fu_1172_p4;
wire   [0:0] icmp_ln318_4_fu_1204_p2;
wire   [0:0] icmp_ln318_5_fu_1210_p2;
wire   [18:0] x_l_I_V_24_fu_1222_p2;
wire   [18:0] x_l_I_V_25_fu_1228_p3;
wire   [0:0] icmp_ln1494_2_fu_1248_p2;
wire   [0:0] or_ln318_2_fu_1216_p2;
wire   [0:0] xor_ln1494_2_fu_1254_p2;
wire   [16:0] x_l_FH_V_29_fu_1242_p2;
wire   [18:0] x_l_I_V_84_fu_1236_p2;
wire   [16:0] p_Result_59_fu_1350_p4;
wire   [16:0] res_FH_V_35_fu_1359_p3;
wire   [3:0] p_Result_22_fu_1365_p4;
wire   [16:0] trunc_ln318_3_fu_1384_p3;
wire   [18:0] zext_ln318_3_fu_1391_p1;
wire   [16:0] mul_FH_V_2_fu_1375_p4;
wire   [0:0] icmp_ln318_6_fu_1395_p2;
wire   [0:0] icmp_ln318_7_fu_1400_p2;
wire   [18:0] x_l_I_V_28_fu_1411_p2;
wire   [18:0] x_l_I_V_29_fu_1416_p3;
wire   [0:0] icmp_ln1494_3_fu_1444_p2;
wire   [0:0] or_ln318_3_fu_1405_p2;
wire   [0:0] xor_ln1494_3_fu_1449_p2;
wire   [0:0] and_ln318_4_fu_1455_p2;
wire   [16:0] p_Result_60_fu_1434_p4;
wire   [16:0] x_l_FH_V_31_fu_1429_p2;
wire   [18:0] x_l_I_V_86_fu_1423_p2;
wire   [16:0] res_FH_V_36_fu_1461_p3;
wire   [4:0] p_Result_23_fu_1483_p4;
wire   [16:0] trunc_ln318_4_fu_1502_p3;
wire   [18:0] x_l_I_V_87_fu_1476_p3;
wire   [18:0] zext_ln318_4_fu_1509_p1;
wire   [16:0] x_l_FH_V_32_fu_1469_p3;
wire   [16:0] mul_FH_V_3_fu_1493_p4;
wire   [0:0] icmp_ln318_16_fu_1513_p2;
wire   [0:0] icmp_ln318_17_fu_1519_p2;
wire   [18:0] x_l_I_V_32_fu_1531_p2;
wire   [18:0] x_l_I_V_33_fu_1537_p3;
wire   [0:0] icmp_ln1494_4_fu_1567_p2;
wire   [0:0] or_ln318_4_fu_1525_p2;
wire   [0:0] xor_ln1494_4_fu_1573_p2;
wire   [0:0] and_ln318_5_fu_1579_p2;
wire   [16:0] p_Result_61_fu_1557_p4;
wire   [16:0] x_l_FH_V_33_fu_1551_p2;
wire   [18:0] x_l_I_V_88_fu_1545_p2;
wire   [5:0] p_Result_24_fu_1609_p4;
wire   [16:0] trunc_ln318_5_fu_1640_p3;
wire   [18:0] zext_ln318_5_fu_1647_p1;
wire   [0:0] icmp_ln318_18_fu_1651_p2;
wire   [18:0] x_l_I_V_37_fu_1661_p3;
wire   [0:0] icmp_ln1494_5_fu_1685_p2;
wire   [0:0] or_ln318_5_fu_1656_p2;
wire   [0:0] xor_ln1494_5_fu_1690_p2;
wire   [0:0] and_ln318_6_fu_1696_p2;
wire   [16:0] p_Result_62_fu_1676_p4;
wire   [16:0] x_l_FH_V_35_fu_1672_p2;
wire   [18:0] x_l_I_V_90_fu_1666_p2;
wire   [16:0] res_FH_V_38_fu_1702_p3;
wire   [6:0] p_Result_25_fu_1723_p4;
wire   [16:0] trunc_ln318_6_fu_1742_p3;
wire   [18:0] x_l_I_V_91_fu_1716_p3;
wire   [18:0] zext_ln318_6_fu_1749_p1;
wire   [16:0] x_l_FH_V_36_fu_1709_p3;
wire   [16:0] mul_FH_V_5_fu_1733_p4;
wire   [0:0] icmp_ln318_20_fu_1753_p2;
wire   [0:0] icmp_ln318_21_fu_1759_p2;
wire   [18:0] x_l_I_V_40_fu_1771_p2;
wire   [18:0] x_l_I_V_41_fu_1777_p3;
wire   [0:0] icmp_ln1494_6_fu_1807_p2;
wire   [0:0] or_ln318_6_fu_1765_p2;
wire   [0:0] xor_ln1494_6_fu_1813_p2;
wire   [0:0] and_ln318_7_fu_1819_p2;
wire   [16:0] p_Result_63_fu_1797_p4;
wire   [16:0] x_l_FH_V_37_fu_1791_p2;
wire   [18:0] x_l_I_V_92_fu_1785_p2;
wire   [7:0] p_Result_26_fu_1849_p4;
wire   [16:0] trunc_ln318_7_fu_1868_p3;
wire   [18:0] x_l_I_V_93_fu_1841_p3;
wire   [18:0] zext_ln318_7_fu_1875_p1;
wire   [16:0] x_l_FH_V_38_fu_1833_p3;
wire   [16:0] mul_FH_V_6_fu_1859_p4;
wire   [0:0] icmp_ln318_22_fu_1879_p2;
wire   [0:0] icmp_ln318_23_fu_1885_p2;
wire   [18:0] x_l_I_V_44_fu_1897_p2;
wire   [18:0] x_l_I_V_45_fu_1903_p3;
wire   [0:0] icmp_ln1494_7_fu_1923_p2;
wire   [0:0] or_ln318_7_fu_1891_p2;
wire   [0:0] xor_ln1494_7_fu_1929_p2;
wire   [16:0] x_l_FH_V_39_fu_1917_p2;
wire   [18:0] x_l_I_V_94_fu_1911_p2;
wire   [16:0] p_Result_64_fu_1957_p4;
wire   [16:0] res_FH_V_fu_1966_p3;
wire   [8:0] p_Result_27_fu_1972_p4;
wire   [16:0] mul_FH_V_7_fu_1982_p3;
wire   [0:0] icmp_ln1498_fu_1994_p2;
wire   [0:0] icmp_ln1494_9_fu_1999_p2;
wire   [0:0] icmp_ln331_fu_2010_p2;
wire   [0:0] xor_ln331_7_fu_2015_p2;
wire   [18:0] x_l_I_V_48_fu_2021_p2;
wire   [16:0] xor_ln703_fu_2033_p2;
wire   [0:0] icmp_ln1494_8_fu_1989_p2;
wire   [0:0] and_ln318_fu_2004_p2;
wire   [0:0] or_ln318_16_fu_2054_p2;
wire   [16:0] p_Result_65_fu_2044_p4;
wire   [16:0] x_l_FH_V_41_fu_2039_p2;
wire   [18:0] x_l_I_V_96_fu_2026_p3;
wire   [16:0] res_FH_V_40_fu_2060_p3;
wire   [7:0] tmp_20_fu_2100_p4;
wire   [1:0] tmp_s_fu_2090_p4;
wire   [16:0] x_l_FH_V_42_fu_2076_p3;
wire   [16:0] mul_FH_V_8_fu_2110_p4;
wire   [16:0] x_l_FL_V_15_fu_2068_p3;
wire   [16:0] mul_FL_V_fu_2119_p3;
wire   [0:0] icmp_ln318_8_fu_2127_p2;
wire   [0:0] delta_V_fu_2133_p2;
wire   [0:0] xor_ln331_fu_2145_p2;
wire   [0:0] icmp_ln1495_fu_2157_p2;
wire   [0:0] or_ln331_fu_2151_p2;
wire   [0:0] xor_ln1495_fu_2163_p2;
wire   [18:0] x_l_I_V_97_fu_2083_p3;
wire   [0:0] and_ln331_fu_2169_p2;
wire   [18:0] x_l_I_V_51_fu_2183_p2;
wire   [16:0] p_neg168_fu_2175_p3;
wire   [16:0] sub_ln703_fu_2197_p2;
wire   [0:0] icmp_ln1494_10_fu_2231_p2;
wire   [0:0] xor_ln1494_8_fu_2237_p2;
wire   [0:0] or_ln318_8_fu_2139_p2;
wire   [0:0] and_ln318_9_fu_2243_p2;
wire   [0:0] icmp_ln1498_1_fu_2225_p2;
wire   [0:0] and_ln318_10_fu_2249_p2;
wire   [16:0] p_Result_66_fu_2215_p4;
wire   [16:0] x_l_FL_V_fu_2209_p2;
wire   [16:0] x_l_FH_V_43_fu_2203_p2;
wire   [18:0] x_l_I_V_98_fu_2189_p3;
wire   [6:0] tmp_21_fu_2297_p4;
wire   [3:0] tmp_7_fu_2287_p4;
wire   [16:0] x_l_FH_V_44_fu_2271_p3;
wire   [16:0] mul_FH_V_9_fu_2307_p4;
wire   [16:0] x_l_FL_V_16_fu_2263_p3;
wire   [16:0] mul_FL_V_1_fu_2316_p3;
wire   [0:0] icmp_ln318_9_fu_2324_p2;
wire   [0:0] delta_V_1_fu_2330_p2;
wire   [0:0] xor_ln331_1_fu_2342_p2;
wire   [0:0] icmp_ln1495_1_fu_2354_p2;
wire   [0:0] or_ln331_1_fu_2348_p2;
wire   [0:0] xor_ln1495_1_fu_2360_p2;
wire   [18:0] x_l_I_V_99_fu_2279_p3;
wire   [0:0] and_ln331_1_fu_2366_p2;
wire   [18:0] x_l_I_V_54_fu_2380_p2;
wire   [16:0] p_neg169_fu_2372_p3;
wire   [16:0] sub_ln703_3_fu_2394_p2;
wire   [0:0] icmp_ln1494_11_fu_2418_p2;
wire   [0:0] xor_ln1494_9_fu_2424_p2;
wire   [0:0] or_ln318_9_fu_2336_p2;
wire   [0:0] and_ln318_11_fu_2430_p2;
wire   [0:0] icmp_ln1498_2_fu_2412_p2;
wire   [16:0] x_l_FL_V_3_fu_2406_p2;
wire   [16:0] x_l_FH_V_45_fu_2400_p2;
wire   [18:0] x_l_I_V_100_fu_2386_p3;
wire   [16:0] p_Result_67_fu_2466_p4;
wire   [16:0] res_FH_V_42_fu_2475_p3;
wire   [5:0] tmp_22_fu_2491_p4;
wire   [5:0] tmp_9_fu_2481_p4;
wire   [16:0] mul_FH_V_10_fu_2501_p4;
wire   [16:0] mul_FL_V_2_fu_2510_p3;
wire   [0:0] icmp_ln318_10_fu_2518_p2;
wire   [0:0] delta_V_2_fu_2523_p2;
wire   [0:0] xor_ln331_2_fu_2534_p2;
wire   [0:0] icmp_ln1495_2_fu_2546_p2;
wire   [0:0] or_ln331_2_fu_2540_p2;
wire   [0:0] xor_ln1495_2_fu_2551_p2;
wire   [0:0] and_ln331_2_fu_2557_p2;
wire   [18:0] x_l_I_V_57_fu_2571_p2;
wire   [16:0] p_neg170_fu_2563_p3;
wire   [16:0] sub_ln703_6_fu_2583_p2;
wire   [0:0] icmp_ln1494_12_fu_2614_p2;
wire   [0:0] xor_ln1494_10_fu_2619_p2;
wire   [0:0] or_ln318_10_fu_2528_p2;
wire   [0:0] and_ln318_13_fu_2625_p2;
wire   [0:0] icmp_ln1498_3_fu_2609_p2;
wire   [0:0] and_ln318_14_fu_2631_p2;
wire   [16:0] p_Result_68_fu_2599_p4;
wire   [16:0] x_l_FL_V_5_fu_2594_p2;
wire   [16:0] x_l_FH_V_47_fu_2589_p2;
wire   [18:0] x_l_I_V_102_fu_2576_p3;
wire   [16:0] res_FH_V_43_fu_2637_p3;
wire   [4:0] tmp_23_fu_2676_p4;
wire   [7:0] tmp_10_fu_2666_p4;
wire   [16:0] x_l_FH_V_48_fu_2652_p3;
wire   [16:0] mul_FH_V_11_fu_2686_p4;
wire   [16:0] x_l_FL_V_18_fu_2645_p3;
wire   [16:0] mul_FL_V_3_fu_2695_p3;
wire   [0:0] icmp_ln318_11_fu_2703_p2;
wire   [0:0] delta_V_3_fu_2709_p2;
wire   [0:0] xor_ln331_3_fu_2721_p2;
wire   [0:0] icmp_ln1495_3_fu_2733_p2;
wire   [0:0] or_ln331_3_fu_2727_p2;
wire   [0:0] xor_ln1495_3_fu_2739_p2;
wire   [18:0] x_l_I_V_103_fu_2659_p3;
wire   [0:0] and_ln331_3_fu_2745_p2;
wire   [18:0] x_l_I_V_60_fu_2759_p2;
wire   [16:0] p_neg171_fu_2751_p3;
wire   [16:0] sub_ln703_9_fu_2773_p2;
wire   [0:0] icmp_ln1494_13_fu_2807_p2;
wire   [0:0] xor_ln1494_11_fu_2813_p2;
wire   [0:0] or_ln318_11_fu_2715_p2;
wire   [0:0] and_ln318_15_fu_2819_p2;
wire   [0:0] icmp_ln1498_4_fu_2801_p2;
wire   [0:0] and_ln318_16_fu_2825_p2;
wire   [16:0] p_Result_69_fu_2791_p4;
wire   [16:0] x_l_FL_V_7_fu_2785_p2;
wire   [16:0] x_l_FH_V_49_fu_2779_p2;
wire   [18:0] x_l_I_V_104_fu_2765_p3;
wire   [3:0] tmp_24_fu_2873_p4;
wire   [9:0] tmp_11_fu_2863_p4;
wire   [16:0] x_l_FH_V_50_fu_2847_p3;
wire   [16:0] mul_FH_V_12_fu_2883_p4;
wire   [16:0] x_l_FL_V_19_fu_2839_p3;
wire   [16:0] mul_FL_V_4_fu_2892_p3;
wire   [0:0] icmp_ln318_12_fu_2900_p2;
wire   [0:0] delta_V_4_fu_2906_p2;
wire   [0:0] xor_ln331_4_fu_2918_p2;
wire   [0:0] icmp_ln1495_4_fu_2930_p2;
wire   [0:0] or_ln331_4_fu_2924_p2;
wire   [0:0] xor_ln1495_4_fu_2936_p2;
wire   [18:0] x_l_I_V_105_fu_2855_p3;
wire   [0:0] and_ln331_4_fu_2942_p2;
wire   [18:0] x_l_I_V_63_fu_2956_p2;
wire   [16:0] p_neg172_fu_2948_p3;
wire   [16:0] sub_ln703_12_fu_2970_p2;
wire   [0:0] icmp_ln1494_14_fu_2994_p2;
wire   [0:0] xor_ln1494_12_fu_3000_p2;
wire   [0:0] or_ln318_12_fu_2912_p2;
wire   [0:0] and_ln318_17_fu_3006_p2;
wire   [0:0] icmp_ln1498_5_fu_2988_p2;
wire   [16:0] x_l_FL_V_9_fu_2982_p2;
wire   [16:0] x_l_FH_V_51_fu_2976_p2;
wire   [18:0] x_l_I_V_106_fu_2962_p3;
wire   [16:0] p_Result_70_fu_3049_p4;
wire   [16:0] res_FH_V_45_fu_3058_p3;
wire   [2:0] tmp_25_fu_3074_p4;
wire   [11:0] tmp_12_fu_3064_p4;
wire   [16:0] mul_FH_V_13_fu_3084_p4;
wire   [16:0] mul_FL_V_5_fu_3093_p3;
wire   [0:0] icmp_ln318_13_fu_3101_p2;
wire   [0:0] delta_V_5_fu_3106_p2;
wire   [0:0] xor_ln331_5_fu_3117_p2;
wire   [0:0] icmp_ln1495_5_fu_3129_p2;
wire   [0:0] or_ln331_5_fu_3123_p2;
wire   [0:0] xor_ln1495_5_fu_3134_p2;
wire   [0:0] and_ln331_5_fu_3140_p2;
wire   [18:0] x_l_I_V_66_fu_3154_p2;
wire   [16:0] p_neg173_fu_3146_p3;
wire   [16:0] sub_ln703_15_fu_3166_p2;
wire   [0:0] icmp_ln1494_15_fu_3197_p2;
wire   [0:0] xor_ln1494_13_fu_3202_p2;
wire   [0:0] or_ln318_13_fu_3111_p2;
wire   [0:0] and_ln318_19_fu_3208_p2;
wire   [0:0] icmp_ln1498_6_fu_3192_p2;
wire   [0:0] and_ln318_20_fu_3214_p2;
wire   [16:0] p_Result_71_fu_3182_p4;
wire   [16:0] x_l_FL_V_11_fu_3177_p2;
wire   [16:0] x_l_FH_V_53_fu_3172_p2;
wire   [18:0] x_l_I_V_108_fu_3159_p3;
wire   [16:0] res_FH_V_46_fu_3220_p3;
wire   [1:0] tmp_26_fu_3259_p4;
wire   [13:0] tmp_13_fu_3249_p4;
wire   [16:0] x_l_FH_V_54_fu_3235_p3;
wire   [16:0] mul_FH_V_14_fu_3269_p4;
wire   [16:0] x_l_FL_V_21_fu_3228_p3;
wire   [16:0] mul_FL_V_6_fu_3278_p3;
wire   [0:0] icmp_ln318_14_fu_3286_p2;
wire   [0:0] delta_V_6_fu_3292_p2;
wire   [0:0] xor_ln331_6_fu_3304_p2;
wire   [0:0] icmp_ln1495_6_fu_3316_p2;
wire   [0:0] or_ln331_6_fu_3310_p2;
wire   [0:0] xor_ln1495_6_fu_3322_p2;
wire   [18:0] x_l_I_V_109_fu_3242_p3;
wire   [0:0] and_ln331_6_fu_3328_p2;
wire   [18:0] x_l_I_V_69_fu_3342_p2;
wire   [16:0] p_neg174_fu_3334_p3;
wire   [16:0] sub_ln703_18_fu_3356_p2;
wire   [0:0] icmp_ln1494_16_fu_3390_p2;
wire   [0:0] xor_ln1494_14_fu_3396_p2;
wire   [0:0] or_ln318_14_fu_3298_p2;
wire   [0:0] and_ln318_21_fu_3402_p2;
wire   [0:0] icmp_ln1498_7_fu_3384_p2;
wire   [0:0] and_ln318_22_fu_3408_p2;
wire   [16:0] p_Result_72_fu_3374_p4;
wire   [16:0] x_l_FL_V_13_fu_3368_p2;
wire   [16:0] x_l_FH_V_55_fu_3362_p2;
wire   [18:0] x_l_I_V_110_fu_3348_p3;
wire   [16:0] res_FH_V_47_fu_3414_p3;
wire   [15:0] trunc_ln104_7_fu_3446_p1;
wire   [0:0] tmp_56_fu_3458_p3;
wire   [16:0] x_l_FH_V_56_fu_3430_p3;
wire   [16:0] mul_FH_V_15_fu_3466_p4;
wire   [16:0] x_l_FL_V_14_fu_3422_p3;
wire   [16:0] mul_FL_V_7_fu_3450_p3;
wire   [0:0] icmp_ln318_15_fu_3475_p2;
wire   [0:0] icmp_ln1496_fu_3481_p2;
wire   [18:0] x_l_I_V_111_fu_3438_p3;
wire   [0:0] icmp_ln1494_17_fu_3509_p2;
wire   [0:0] xor_ln1494_15_fu_3515_p2;
wire   [0:0] or_ln318_15_fu_3487_p2;
wire   [0:0] and_ln318_23_fu_3521_p2;
wire   [0:0] icmp_ln1498_8_fu_3503_p2;
wire   [0:0] and_ln318_24_fu_3527_p2;
wire   [16:0] p_Result_73_fu_3493_p4;
wire   [16:0] res_FH_V_31_fu_3533_p3;
wire   [17:0] zext_ln703_fu_3541_p1;
wire   [17:0] res_FH_l_V_fu_3545_p2;
wire   [0:0] p_Result_40_fu_3557_p3;
wire   [7:0] res_I_V_14_fu_3565_p2;
wire   [16:0] res_FH_V_48_fu_3551_p2;
wire   [7:0] res_I_V_23_fu_3570_p3;
wire   [15:0] tmp_27_fu_3577_p4;
wire   [0:0] p_Result_s_fu_3042_p3;
wire   [23:0] trunc_ln4_fu_3587_p3;
wire   [23:0] select_ln99_fu_3595_p3;
reg    ap_ce_reg;
reg   [31:0] x_int_reg;
reg   [23:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        and_ln318_12_reg_3828 <= and_ln318_12_fu_2436_p2;
        and_ln318_18_reg_3863 <= and_ln318_18_fu_3012_p2;
        and_ln318_3_reg_3687 <= and_ln318_3_fu_1260_p2;
        and_ln318_8_reg_3800 <= and_ln318_8_fu_1935_p2;
        icmp_ln318_19_reg_3783 <= icmp_ln318_19_fu_1628_p2;
        icmp_ln318_1_reg_3636 <= icmp_ln318_1_fu_578_p2;
        icmp_ln318_1_reg_3636_pp0_iter1_reg <= icmp_ln318_1_reg_3636;
        icmp_ln489_3_reg_3625 <= icmp_ln489_3_fu_556_p2;
        icmp_ln489_7_reg_3648 <= icmp_ln489_7_fu_877_p2;
        mul_FH_V_4_reg_3778[16 : 6] <= mul_FH_V_4_fu_1619_p4[16 : 6];
        res_FH_V_34_reg_3681 <= res_FH_V_34_fu_1134_p3;
        res_FH_V_37_reg_3758 <= res_FH_V_37_fu_1585_p3;
        res_FH_V_39_reg_3794 <= res_FH_V_39_fu_1825_p3;
        res_FH_V_41_reg_3822 <= res_FH_V_41_fu_2255_p3;
        res_FH_V_44_reg_3857 <= res_FH_V_44_fu_2831_p3;
        res_I_V_18_reg_3619 <= res_I_V_18_fu_516_p3;
        res_I_V_22_reg_3642 <= res_I_V_22_fu_853_p3;
        res_I_V_reg_3666 <= res_I_V_fu_931_p3;
        res_I_V_reg_3666_pp0_iter3_reg <= res_I_V_reg_3666;
        res_I_V_reg_3666_pp0_iter4_reg <= res_I_V_reg_3666_pp0_iter3_reg;
        res_I_V_reg_3666_pp0_iter5_reg <= res_I_V_reg_3666_pp0_iter4_reg;
        res_I_V_reg_3666_pp0_iter6_reg <= res_I_V_reg_3666_pp0_iter5_reg;
        sub_ln248_2_reg_3631 <= sub_ln248_2_fu_562_p2;
        tmp_16_reg_3713 <= {{res_I_V_fu_931_p3[7:3]}};
        tmp_17_reg_3723 <= {{res_I_V_fu_931_p3[7:4]}};
        tmp_18_reg_3733 <= {{res_I_V_fu_931_p3[7:5]}};
        tmp_18_reg_3733_pp0_iter3_reg <= tmp_18_reg_3733;
        tmp_19_reg_3743 <= {{res_I_V_fu_931_p3[7:6]}};
        tmp_19_reg_3743_pp0_iter3_reg <= tmp_19_reg_3743;
        tmp_45_reg_3753 <= res_I_V_fu_931_p3[32'd7];
        tmp_45_reg_3753_pp0_iter3_reg <= tmp_45_reg_3753;
        trunc_ln104_2_reg_3708 <= trunc_ln104_2_fu_1282_p1;
        trunc_ln104_3_reg_3718 <= trunc_ln104_3_fu_1296_p1;
        trunc_ln104_4_reg_3728 <= trunc_ln104_4_fu_1310_p1;
        trunc_ln104_5_reg_3738 <= trunc_ln104_5_fu_1324_p1;
        trunc_ln104_5_reg_3738_pp0_iter3_reg <= trunc_ln104_5_reg_3738;
        trunc_ln104_6_reg_3748 <= trunc_ln104_6_fu_1338_p1;
        trunc_ln104_6_reg_3748_pp0_iter3_reg <= trunc_ln104_6_reg_3748;
        trunc_ln731_reg_3608 <= trunc_ln731_fu_302_p1;
        trunc_ln731_reg_3608_pp0_iter1_reg <= trunc_ln731_reg_3608;
        x_l_FH_V_30_reg_3692[16 : 1] <= x_l_FH_V_30_fu_1266_p3[16 : 1];
        x_l_FH_V_34_reg_3764[16 : 1] <= x_l_FH_V_34_fu_1593_p3[16 : 1];
        x_l_FH_V_40_reg_3805[16 : 1] <= x_l_FH_V_40_fu_1941_p3[16 : 1];
        x_l_FH_V_46_reg_3840 <= x_l_FH_V_46_fu_2450_p3;
        x_l_FH_V_52_reg_3875 <= x_l_FH_V_52_fu_3026_p3;
        x_l_FL_V_17_reg_3833[16 : 12] <= x_l_FL_V_17_fu_2442_p3[16 : 12];
        x_l_FL_V_20_reg_3868[16 : 6] <= x_l_FL_V_20_fu_3018_p3[16 : 6];
        x_l_I_V_101_reg_3849 <= x_l_I_V_101_fu_2458_p3;
        x_l_I_V_107_reg_3884 <= x_l_I_V_107_fu_3034_p3;
        x_l_I_V_36_reg_3789 <= x_l_I_V_36_fu_1634_p2;
        x_l_I_V_74_reg_3613 <= x_l_I_V_74_fu_508_p3;
        x_l_I_V_79_reg_3653 <= x_l_I_V_79_fu_901_p3;
        x_l_I_V_85_reg_3699 <= x_l_I_V_85_fu_1274_p3;
        x_l_I_V_89_reg_3770 <= x_l_I_V_89_fu_1601_p3;
        x_l_I_V_95_reg_3813 <= x_l_I_V_95_fu_1949_p3;
        x_read_reg_3603 <= x_int_reg;
        x_read_reg_3603_pp0_iter1_reg <= x_read_reg_3603;
        x_read_reg_3603_pp0_iter2_reg <= x_read_reg_3603_pp0_iter1_reg;
        x_read_reg_3603_pp0_iter3_reg <= x_read_reg_3603_pp0_iter2_reg;
        x_read_reg_3603_pp0_iter4_reg <= x_read_reg_3603_pp0_iter3_reg;
        x_read_reg_3603_pp0_iter5_reg <= x_read_reg_3603_pp0_iter4_reg;
        x_read_reg_3603_pp0_iter6_reg <= x_read_reg_3603_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln99_fu_3595_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln318_1_reg_3636 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        x_l_I_V_17_reg_3661 <= x_l_I_V_17_fu_909_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln99_fu_3595_p3;
    end
end

assign add_ln248_fu_326_p2 = ($signed(sext_ln640_fu_316_p1) + $signed(3'd7));

assign and_ln318_10_fu_2249_p2 = (icmp_ln1498_1_fu_2225_p2 & and_ln318_9_fu_2243_p2);

assign and_ln318_11_fu_2430_p2 = (xor_ln1494_9_fu_2424_p2 & or_ln318_9_fu_2336_p2);

assign and_ln318_12_fu_2436_p2 = (icmp_ln1498_2_fu_2412_p2 & and_ln318_11_fu_2430_p2);

assign and_ln318_13_fu_2625_p2 = (xor_ln1494_10_fu_2619_p2 & or_ln318_10_fu_2528_p2);

assign and_ln318_14_fu_2631_p2 = (icmp_ln1498_3_fu_2609_p2 & and_ln318_13_fu_2625_p2);

assign and_ln318_15_fu_2819_p2 = (xor_ln1494_11_fu_2813_p2 & or_ln318_11_fu_2715_p2);

assign and_ln318_16_fu_2825_p2 = (icmp_ln1498_4_fu_2801_p2 & and_ln318_15_fu_2819_p2);

assign and_ln318_17_fu_3006_p2 = (xor_ln1494_12_fu_3000_p2 & or_ln318_12_fu_2912_p2);

assign and_ln318_18_fu_3012_p2 = (icmp_ln1498_5_fu_2988_p2 & and_ln318_17_fu_3006_p2);

assign and_ln318_19_fu_3208_p2 = (xor_ln1494_13_fu_3202_p2 & or_ln318_13_fu_3111_p2);

assign and_ln318_1_fu_987_p2 = (xor_ln1494_fu_981_p2 & or_ln318_fu_954_p2);

assign and_ln318_20_fu_3214_p2 = (icmp_ln1498_6_fu_3192_p2 & and_ln318_19_fu_3208_p2);

assign and_ln318_21_fu_3402_p2 = (xor_ln1494_14_fu_3396_p2 & or_ln318_14_fu_3298_p2);

assign and_ln318_22_fu_3408_p2 = (icmp_ln1498_7_fu_3384_p2 & and_ln318_21_fu_3402_p2);

assign and_ln318_23_fu_3521_p2 = (xor_ln1494_15_fu_3515_p2 & or_ln318_15_fu_3487_p2);

assign and_ln318_24_fu_3527_p2 = (icmp_ln1498_8_fu_3503_p2 & and_ln318_23_fu_3521_p2);

assign and_ln318_2_fu_1128_p2 = (xor_ln1494_1_fu_1122_p2 & or_ln318_1_fu_1074_p2);

assign and_ln318_3_fu_1260_p2 = (xor_ln1494_2_fu_1254_p2 & or_ln318_2_fu_1216_p2);

assign and_ln318_4_fu_1455_p2 = (xor_ln1494_3_fu_1449_p2 & or_ln318_3_fu_1405_p2);

assign and_ln318_5_fu_1579_p2 = (xor_ln1494_4_fu_1573_p2 & or_ln318_4_fu_1525_p2);

assign and_ln318_6_fu_1696_p2 = (xor_ln1494_5_fu_1690_p2 & or_ln318_5_fu_1656_p2);

assign and_ln318_7_fu_1819_p2 = (xor_ln1494_6_fu_1813_p2 & or_ln318_6_fu_1765_p2);

assign and_ln318_8_fu_1935_p2 = (xor_ln1494_7_fu_1929_p2 & or_ln318_7_fu_1891_p2);

assign and_ln318_9_fu_2243_p2 = (xor_ln1494_8_fu_2237_p2 & or_ln318_8_fu_2139_p2);

assign and_ln318_fu_2004_p2 = (icmp_ln1498_fu_1994_p2 & icmp_ln1494_9_fu_1999_p2);

assign and_ln331_1_fu_2366_p2 = (xor_ln1495_1_fu_2360_p2 & or_ln331_1_fu_2348_p2);

assign and_ln331_2_fu_2557_p2 = (xor_ln1495_2_fu_2551_p2 & or_ln331_2_fu_2540_p2);

assign and_ln331_3_fu_2745_p2 = (xor_ln1495_3_fu_2739_p2 & or_ln331_3_fu_2727_p2);

assign and_ln331_4_fu_2942_p2 = (xor_ln1495_4_fu_2936_p2 & or_ln331_4_fu_2924_p2);

assign and_ln331_5_fu_3140_p2 = (xor_ln1495_5_fu_3134_p2 & or_ln331_5_fu_3123_p2);

assign and_ln331_6_fu_3328_p2 = (xor_ln1495_6_fu_3322_p2 & or_ln331_6_fu_3310_p2);

assign and_ln331_fu_2169_p2 = (xor_ln1495_fu_2163_p2 & or_ln331_fu_2151_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign delta_V_1_fu_2330_p2 = ((x_l_FL_V_16_fu_2263_p3 < mul_FL_V_1_fu_2316_p3) ? 1'b1 : 1'b0);

assign delta_V_2_fu_2523_p2 = ((x_l_FL_V_17_reg_3833 < mul_FL_V_2_fu_2510_p3) ? 1'b1 : 1'b0);

assign delta_V_3_fu_2709_p2 = ((x_l_FL_V_18_fu_2645_p3 < mul_FL_V_3_fu_2695_p3) ? 1'b1 : 1'b0);

assign delta_V_4_fu_2906_p2 = ((x_l_FL_V_19_fu_2839_p3 < mul_FL_V_4_fu_2892_p3) ? 1'b1 : 1'b0);

assign delta_V_5_fu_3106_p2 = ((x_l_FL_V_20_reg_3868 < mul_FL_V_5_fu_3093_p3) ? 1'b1 : 1'b0);

assign delta_V_6_fu_3292_p2 = ((x_l_FL_V_21_fu_3228_p3 < mul_FL_V_6_fu_3278_p3) ? 1'b1 : 1'b0);

assign delta_V_fu_2133_p2 = ((x_l_FL_V_15_fu_2068_p3 < mul_FL_V_fu_2119_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_10_fu_2231_p2 = ((mul_FH_V_8_fu_2110_p4 < x_l_FH_V_42_fu_2076_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_2418_p2 = ((mul_FH_V_9_fu_2307_p4 < x_l_FH_V_44_fu_2271_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_2614_p2 = ((mul_FH_V_10_fu_2501_p4 < x_l_FH_V_46_reg_3840) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_2807_p2 = ((mul_FH_V_11_fu_2686_p4 < x_l_FH_V_48_fu_2652_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_2994_p2 = ((mul_FH_V_12_fu_2883_p4 < x_l_FH_V_50_fu_2847_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_3197_p2 = ((mul_FH_V_13_fu_3084_p4 < x_l_FH_V_52_reg_3875) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_3390_p2 = ((mul_FH_V_14_fu_3269_p4 < x_l_FH_V_54_fu_3235_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_3509_p2 = ((mul_FH_V_15_fu_3466_p4 < x_l_FH_V_56_fu_3430_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_1116_p2 = ((zext_ln318_1_fu_1058_p1 < x_l_I_V_81_fu_1009_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_1248_p2 = ((zext_ln318_2_fu_1200_p1 < x_l_I_V_83_fu_1150_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_1444_p2 = ((zext_ln318_3_fu_1391_p1 < x_l_I_V_85_reg_3699) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_1567_p2 = ((zext_ln318_4_fu_1509_p1 < x_l_I_V_87_fu_1476_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_1685_p2 = ((zext_ln318_5_fu_1647_p1 < x_l_I_V_89_reg_3770) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1807_p2 = ((zext_ln318_6_fu_1749_p1 < x_l_I_V_91_fu_1716_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1923_p2 = ((zext_ln318_7_fu_1875_p1 < x_l_I_V_93_fu_1841_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_1989_p2 = ((x_l_I_V_95_reg_3813 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_1999_p2 = ((x_l_FH_V_40_reg_3805 > mul_FH_V_7_fu_1982_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_976_p2 = ((zext_ln318_fu_945_p1 < x_l_I_V_79_reg_3653) ? 1'b1 : 1'b0);

assign icmp_ln1495_1_fu_2354_p2 = ((x_l_FH_V_44_fu_2271_p3 < mul_FH_V_9_fu_2307_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_2_fu_2546_p2 = ((x_l_FH_V_46_reg_3840 < mul_FH_V_10_fu_2501_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_3_fu_2733_p2 = ((x_l_FH_V_48_fu_2652_p3 < mul_FH_V_11_fu_2686_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_4_fu_2930_p2 = ((x_l_FH_V_50_fu_2847_p3 < mul_FH_V_12_fu_2883_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_5_fu_3129_p2 = ((x_l_FH_V_52_reg_3875 < mul_FH_V_13_fu_3084_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_6_fu_3316_p2 = ((x_l_FH_V_54_fu_3235_p3 < mul_FH_V_14_fu_3269_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_fu_2157_p2 = ((x_l_FH_V_42_fu_2076_p3 < mul_FH_V_8_fu_2110_p4) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_3481_p2 = ((x_l_FL_V_14_fu_3422_p3 < mul_FL_V_7_fu_3450_p3) ? 1'b1 : 1'b0);

assign icmp_ln1498_1_fu_2225_p2 = ((x_l_I_V_97_fu_2083_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_2_fu_2412_p2 = ((x_l_I_V_99_fu_2279_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_3_fu_2609_p2 = ((x_l_I_V_101_reg_3849 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_4_fu_2801_p2 = ((x_l_I_V_103_fu_2659_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_5_fu_2988_p2 = ((x_l_I_V_105_fu_2855_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_6_fu_3192_p2 = ((x_l_I_V_107_reg_3884 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_7_fu_3384_p2 = ((x_l_I_V_109_fu_3242_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_8_fu_3503_p2 = ((x_l_I_V_111_fu_3438_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_fu_1994_p2 = ((x_l_I_V_95_reg_3813 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_10_fu_2518_p2 = ((x_l_FH_V_46_reg_3840 != mul_FH_V_10_fu_2501_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_11_fu_2703_p2 = ((x_l_FH_V_48_fu_2652_p3 != mul_FH_V_11_fu_2686_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_12_fu_2900_p2 = ((x_l_FH_V_50_fu_2847_p3 != mul_FH_V_12_fu_2883_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_13_fu_3101_p2 = ((x_l_FH_V_52_reg_3875 != mul_FH_V_13_fu_3084_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_14_fu_3286_p2 = ((x_l_FH_V_54_fu_3235_p3 != mul_FH_V_14_fu_3269_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_15_fu_3475_p2 = ((x_l_FH_V_56_fu_3430_p3 != mul_FH_V_15_fu_3466_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_16_fu_1513_p2 = ((x_l_I_V_87_fu_1476_p3 != zext_ln318_4_fu_1509_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_17_fu_1519_p2 = ((x_l_FH_V_32_fu_1469_p3 < mul_FH_V_3_fu_1493_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_18_fu_1651_p2 = ((x_l_I_V_89_reg_3770 != zext_ln318_5_fu_1647_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_19_fu_1628_p2 = ((x_l_FH_V_34_fu_1593_p3 < mul_FH_V_4_fu_1619_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_1_fu_578_p2 = ((tmp_38_fu_568_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_20_fu_1753_p2 = ((x_l_I_V_91_fu_1716_p3 != zext_ln318_6_fu_1749_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_21_fu_1759_p2 = ((x_l_FH_V_36_fu_1709_p3 < mul_FH_V_5_fu_1733_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_22_fu_1879_p2 = ((x_l_I_V_93_fu_1841_p3 != zext_ln318_7_fu_1875_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_23_fu_1885_p2 = ((x_l_FH_V_38_fu_1833_p3 < mul_FH_V_6_fu_1859_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_2_fu_1062_p2 = ((x_l_I_V_81_fu_1009_p3 != zext_ln318_1_fu_1058_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_3_fu_1068_p2 = ((p_Val2_23_fu_1001_p3 < mul_FH_V_fu_1030_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_4_fu_1204_p2 = ((x_l_I_V_83_fu_1150_p3 != zext_ln318_2_fu_1200_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_5_fu_1210_p2 = ((x_l_FH_V_28_fu_1142_p3 < mul_FH_V_1_fu_1172_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_6_fu_1395_p2 = ((x_l_I_V_85_reg_3699 != zext_ln318_3_fu_1391_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_7_fu_1400_p2 = ((x_l_FH_V_30_reg_3692 < mul_FH_V_2_fu_1375_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_8_fu_2127_p2 = ((x_l_FH_V_42_fu_2076_p3 != mul_FH_V_8_fu_2110_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_9_fu_2324_p2 = ((x_l_FH_V_44_fu_2271_p3 != mul_FH_V_9_fu_2307_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_949_p2 = ((x_l_I_V_79_reg_3653 != zext_ln318_fu_945_p1) ? 1'b1 : 1'b0);

assign icmp_ln331_fu_2010_p2 = ((mul_FH_V_7_fu_1982_p3 < x_l_FH_V_40_reg_3805) ? 1'b1 : 1'b0);

assign icmp_ln489_1_fu_392_p2 = ((p_Result_1_fu_378_p4 < zext_ln489_fu_388_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_2_fu_474_p2 = ((p_Result_5_fu_460_p4 < zext_ln489_1_fu_470_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_3_fu_556_p2 = ((p_Result_9_fu_542_p4 < zext_ln489_2_fu_552_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_4_fu_647_p2 = ((p_Result_11_fu_633_p4 < zext_ln489_3_fu_643_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_5_fu_729_p2 = ((p_Result_14_fu_715_p4 < zext_ln489_4_fu_725_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_6_fu_811_p2 = ((p_Result_17_fu_797_p4 < zext_ln489_5_fu_807_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_7_fu_877_p2 = ((trunc_ln640_fu_869_p1 < zext_ln489_6_fu_873_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_fu_320_p2 = ((tmp_fu_306_p4 == 2'd0) ? 1'b1 : 1'b0);

assign mul_FH_V_10_fu_2501_p4 = {{{{3'd0}, {res_I_V_reg_3666_pp0_iter5_reg}}}, {tmp_22_fu_2491_p4}};

assign mul_FH_V_11_fu_2686_p4 = {{{{4'd0}, {res_I_V_reg_3666_pp0_iter5_reg}}}, {tmp_23_fu_2676_p4}};

assign mul_FH_V_12_fu_2883_p4 = {{{{5'd0}, {res_I_V_reg_3666_pp0_iter5_reg}}}, {tmp_24_fu_2873_p4}};

assign mul_FH_V_13_fu_3084_p4 = {{{{6'd0}, {res_I_V_reg_3666_pp0_iter6_reg}}}, {tmp_25_fu_3074_p4}};

assign mul_FH_V_14_fu_3269_p4 = {{{{7'd0}, {res_I_V_reg_3666_pp0_iter6_reg}}}, {tmp_26_fu_3259_p4}};

assign mul_FH_V_15_fu_3466_p4 = {{{{8'd0}, {res_I_V_reg_3666_pp0_iter6_reg}}}, {tmp_56_fu_3458_p3}};

assign mul_FH_V_1_fu_1172_p4 = {{{trunc_ln104_1_fu_1168_p1}, {p_Result_21_fu_1158_p4}}, {12'd2048}};

assign mul_FH_V_2_fu_1375_p4 = {{{trunc_ln104_2_reg_3708}, {p_Result_22_fu_1365_p4}}, {10'd512}};

assign mul_FH_V_3_fu_1493_p4 = {{{trunc_ln104_3_reg_3718}, {p_Result_23_fu_1483_p4}}, {8'd128}};

assign mul_FH_V_4_fu_1619_p4 = {{{trunc_ln104_4_reg_3728}, {p_Result_24_fu_1609_p4}}, {6'd32}};

assign mul_FH_V_5_fu_1733_p4 = {{{trunc_ln104_5_reg_3738_pp0_iter3_reg}, {p_Result_25_fu_1723_p4}}, {4'd8}};

assign mul_FH_V_6_fu_1859_p4 = {{{trunc_ln104_6_reg_3748_pp0_iter3_reg}, {p_Result_26_fu_1849_p4}}, {2'd2}};

assign mul_FH_V_7_fu_1982_p3 = {{res_I_V_reg_3666_pp0_iter4_reg}, {p_Result_27_fu_1972_p4}};

assign mul_FH_V_8_fu_2110_p4 = {{{{1'd0}, {res_I_V_reg_3666_pp0_iter4_reg}}}, {tmp_20_fu_2100_p4}};

assign mul_FH_V_9_fu_2307_p4 = {{{{2'd0}, {res_I_V_reg_3666_pp0_iter4_reg}}}, {tmp_21_fu_2297_p4}};

assign mul_FH_V_fu_1030_p4 = {{{trunc_ln104_fu_1026_p1}, {p_Result_20_fu_1016_p4}}, {14'd8192}};

assign mul_FL_V_1_fu_2316_p3 = {{tmp_7_fu_2287_p4}, {13'd4096}};

assign mul_FL_V_2_fu_2510_p3 = {{tmp_9_fu_2481_p4}, {11'd1024}};

assign mul_FL_V_3_fu_2695_p3 = {{tmp_10_fu_2666_p4}, {9'd256}};

assign mul_FL_V_4_fu_2892_p3 = {{tmp_11_fu_2863_p4}, {7'd64}};

assign mul_FL_V_5_fu_3093_p3 = {{tmp_12_fu_3064_p4}, {5'd16}};

assign mul_FL_V_6_fu_3278_p3 = {{tmp_13_fu_3249_p4}, {3'd4}};

assign mul_FL_V_7_fu_3450_p3 = {{trunc_ln104_7_fu_3446_p1}, {1'd1}};

assign mul_FL_V_fu_2119_p3 = {{tmp_s_fu_2090_p4}, {15'd16384}};

assign or_ln318_10_fu_2528_p2 = (icmp_ln318_10_fu_2518_p2 | delta_V_2_fu_2523_p2);

assign or_ln318_11_fu_2715_p2 = (icmp_ln318_11_fu_2703_p2 | delta_V_3_fu_2709_p2);

assign or_ln318_12_fu_2912_p2 = (icmp_ln318_12_fu_2900_p2 | delta_V_4_fu_2906_p2);

assign or_ln318_13_fu_3111_p2 = (icmp_ln318_13_fu_3101_p2 | delta_V_5_fu_3106_p2);

assign or_ln318_14_fu_3298_p2 = (icmp_ln318_14_fu_3286_p2 | delta_V_6_fu_3292_p2);

assign or_ln318_15_fu_3487_p2 = (icmp_ln318_15_fu_3475_p2 | icmp_ln1496_fu_3481_p2);

assign or_ln318_16_fu_2054_p2 = (icmp_ln1494_8_fu_1989_p2 | and_ln318_fu_2004_p2);

assign or_ln318_1_fu_1074_p2 = (icmp_ln318_3_fu_1068_p2 | icmp_ln318_2_fu_1062_p2);

assign or_ln318_2_fu_1216_p2 = (icmp_ln318_5_fu_1210_p2 | icmp_ln318_4_fu_1204_p2);

assign or_ln318_3_fu_1405_p2 = (icmp_ln318_7_fu_1400_p2 | icmp_ln318_6_fu_1395_p2);

assign or_ln318_4_fu_1525_p2 = (icmp_ln318_17_fu_1519_p2 | icmp_ln318_16_fu_1513_p2);

assign or_ln318_5_fu_1656_p2 = (icmp_ln318_19_reg_3783 | icmp_ln318_18_fu_1651_p2);

assign or_ln318_6_fu_1765_p2 = (icmp_ln318_21_fu_1759_p2 | icmp_ln318_20_fu_1753_p2);

assign or_ln318_7_fu_1891_p2 = (icmp_ln318_23_fu_1885_p2 | icmp_ln318_22_fu_1879_p2);

assign or_ln318_8_fu_2139_p2 = (icmp_ln318_8_fu_2127_p2 | delta_V_fu_2133_p2);

assign or_ln318_9_fu_2336_p2 = (icmp_ln318_9_fu_2324_p2 | delta_V_1_fu_2330_p2);

assign or_ln318_fu_954_p2 = (icmp_ln318_fu_949_p2 | icmp_ln318_1_reg_3636_pp0_iter1_reg);

assign or_ln331_1_fu_2348_p2 = (xor_ln331_1_fu_2342_p2 | icmp_ln318_9_fu_2324_p2);

assign or_ln331_2_fu_2540_p2 = (xor_ln331_2_fu_2534_p2 | icmp_ln318_10_fu_2518_p2);

assign or_ln331_3_fu_2727_p2 = (xor_ln331_3_fu_2721_p2 | icmp_ln318_11_fu_2703_p2);

assign or_ln331_4_fu_2924_p2 = (xor_ln331_4_fu_2918_p2 | icmp_ln318_12_fu_2900_p2);

assign or_ln331_5_fu_3123_p2 = (xor_ln331_5_fu_3117_p2 | icmp_ln318_13_fu_3101_p2);

assign or_ln331_6_fu_3310_p2 = (xor_ln331_6_fu_3304_p2 | icmp_ln318_14_fu_3286_p2);

assign or_ln331_fu_2151_p2 = (xor_ln331_fu_2145_p2 | icmp_ln318_8_fu_2127_p2);

assign p_Result_10_fu_615_p4 = {{res_I_V_19_fu_609_p3[7:3]}};

assign p_Result_11_fu_633_p4 = {{x_l_I_V_75_fu_603_p3[12:6]}};

assign p_Result_13_fu_697_p4 = {{res_I_V_20_fu_689_p3[7:2]}};

assign p_Result_14_fu_715_p4 = {{x_l_I_V_76_fu_681_p3[11:4]}};

assign p_Result_16_fu_779_p4 = {{res_I_V_21_fu_771_p3[7:1]}};

assign p_Result_17_fu_797_p4 = {{x_l_I_V_77_fu_763_p3[10:2]}};

assign p_Result_1_fu_378_p4 = {{x_l_I_V_72_fu_344_p3[15:12]}};

assign p_Result_20_fu_1016_p4 = {{res_FH_V_33_fu_993_p3[16:15]}};

assign p_Result_21_fu_1158_p4 = {{res_FH_V_34_fu_1134_p3[16:14]}};

assign p_Result_22_fu_1365_p4 = {{res_FH_V_35_fu_1359_p3[16:13]}};

assign p_Result_23_fu_1483_p4 = {{res_FH_V_36_fu_1461_p3[16:12]}};

assign p_Result_24_fu_1609_p4 = {{res_FH_V_37_fu_1585_p3[16:11]}};

assign p_Result_25_fu_1723_p4 = {{res_FH_V_38_fu_1702_p3[16:10]}};

assign p_Result_26_fu_1849_p4 = {{res_FH_V_39_fu_1825_p3[16:9]}};

assign p_Result_27_fu_1972_p4 = {{res_FH_V_fu_1966_p3[16:8]}};

assign p_Result_40_fu_3557_p3 = res_FH_l_V_fu_3545_p2[32'd17];

assign p_Result_43_fu_332_p5 = {{zext_ln708_fu_298_p1[18:17]}, {add_ln248_fu_326_p2}, {zext_ln708_fu_298_p1[13:0]}};

assign p_Result_44_fu_404_p5 = {{x_l_I_V_72_fu_344_p3[18:16]}, {sub_ln248_fu_398_p2}, {x_l_I_V_72_fu_344_p3[11:0]}};

assign p_Result_45_fu_416_p4 = {res_I_V_16_fu_352_p3[8 - 1:7], |(1'd1), res_I_V_16_fu_352_p3[5:0]};

assign p_Result_46_fu_486_p5 = {{x_l_I_V_73_fu_426_p3[18:15]}, {sub_ln248_1_fu_480_p2}, {x_l_I_V_73_fu_426_p3[9:0]}};

assign p_Result_47_fu_498_p4 = {res_I_V_17_fu_434_p3[8 - 1:6], |(1'd1), res_I_V_17_fu_434_p3[4:0]};

assign p_Result_48_fu_584_p5 = {{x_l_I_V_74_reg_3613[18:14]}, {sub_ln248_2_reg_3631}, {x_l_I_V_74_reg_3613[7:0]}};

assign p_Result_49_fu_594_p4 = {res_I_V_18_reg_3619[8 - 1:5], |(1'd1), res_I_V_18_reg_3619[3:0]};

assign p_Result_4_fu_442_p4 = {{res_I_V_17_fu_434_p3[7:5]}};

assign p_Result_50_fu_659_p5 = {{x_l_I_V_75_fu_603_p3[18:13]}, {sub_ln248_3_fu_653_p2}, {x_l_I_V_75_fu_603_p3[5:0]}};

assign p_Result_51_fu_671_p4 = {res_I_V_19_fu_609_p3[8 - 1:4], |(1'd1), res_I_V_19_fu_609_p3[2:0]};

assign p_Result_52_fu_741_p5 = {{x_l_I_V_76_fu_681_p3[18:12]}, {sub_ln248_4_fu_735_p2}, {x_l_I_V_76_fu_681_p3[3:0]}};

assign p_Result_53_fu_753_p4 = {res_I_V_20_fu_689_p3[8 - 1:3], |(1'd1), res_I_V_20_fu_689_p3[1:0]};

assign p_Result_54_fu_823_p5 = {{x_l_I_V_77_fu_763_p3[18:11]}, {sub_ln248_5_fu_817_p2}, {x_l_I_V_77_fu_763_p3[1:0]}};

assign p_Result_55_fu_835_p4 = {res_I_V_21_fu_771_p3[8 - 1:2], |(1'd1), res_I_V_21_fu_771_p3[0:0]};

assign p_Result_56_fu_889_p5 = {{x_l_I_V_78_fu_845_p3[18:10]}, {sub_ln248_6_fu_883_p2}};

assign p_Result_57_fu_922_p4 = {res_I_V_22_reg_3642[8-1:1], |(1'd1)};

assign p_Result_58_fu_1106_p4 = {res_FH_V_33_fu_993_p3[17 - 1:16], |(1'd1), res_FH_V_33_fu_993_p3[14:0]};

assign p_Result_59_fu_1350_p4 = {res_FH_V_34_reg_3681[17 - 1:15], |(1'd1), res_FH_V_34_reg_3681[13:0]};

assign p_Result_5_fu_460_p4 = {{x_l_I_V_73_fu_426_p3[14:10]}};

assign p_Result_60_fu_1434_p4 = {res_FH_V_35_fu_1359_p3[17 - 1:14], |(1'd1), res_FH_V_35_fu_1359_p3[12:0]};

assign p_Result_61_fu_1557_p4 = {res_FH_V_36_fu_1461_p3[17 - 1:13], |(1'd1), res_FH_V_36_fu_1461_p3[11:0]};

assign p_Result_62_fu_1676_p4 = {res_FH_V_37_reg_3758[17 - 1:12], |(1'd1), res_FH_V_37_reg_3758[10:0]};

assign p_Result_63_fu_1797_p4 = {res_FH_V_38_fu_1702_p3[17 - 1:11], |(1'd1), res_FH_V_38_fu_1702_p3[9:0]};

assign p_Result_64_fu_1957_p4 = {res_FH_V_39_reg_3794[17 - 1:10], |(1'd1), res_FH_V_39_reg_3794[8:0]};

assign p_Result_65_fu_2044_p4 = {res_FH_V_fu_1966_p3[17 - 1:9], |(1'd1), res_FH_V_fu_1966_p3[7:0]};

assign p_Result_66_fu_2215_p4 = {res_FH_V_40_fu_2060_p3[17 - 1:8], |(1'd1), res_FH_V_40_fu_2060_p3[6:0]};

assign p_Result_67_fu_2466_p4 = {res_FH_V_41_reg_3822[17 - 1:7], |(1'd1), res_FH_V_41_reg_3822[5:0]};

assign p_Result_68_fu_2599_p4 = {res_FH_V_42_fu_2475_p3[17 - 1:6], |(1'd1), res_FH_V_42_fu_2475_p3[4:0]};

assign p_Result_69_fu_2791_p4 = {res_FH_V_43_fu_2637_p3[17 - 1:5], |(1'd1), res_FH_V_43_fu_2637_p3[3:0]};

assign p_Result_70_fu_3049_p4 = {res_FH_V_44_reg_3857[17 - 1:4], |(1'd1), res_FH_V_44_reg_3857[2:0]};

assign p_Result_71_fu_3182_p4 = {res_FH_V_45_fu_3058_p3[17 - 1:3], |(1'd1), res_FH_V_45_fu_3058_p3[1:0]};

assign p_Result_72_fu_3374_p4 = {res_FH_V_46_fu_3220_p3[17 - 1:2], |(1'd1), res_FH_V_46_fu_3220_p3[0:0]};

assign p_Result_73_fu_3493_p4 = {res_FH_V_47_fu_3414_p3[17-1:1], |(1'd1)};

assign p_Result_8_fu_524_p4 = {{res_I_V_18_fu_516_p3[7:4]}};

assign p_Result_9_fu_542_p4 = {{x_l_I_V_74_fu_508_p3[13:8]}};

assign p_Result_s_38_fu_360_p4 = {{res_I_V_16_fu_352_p3[7:6]}};

assign p_Result_s_fu_3042_p3 = x_read_reg_3603_pp0_iter6_reg[32'd31];

assign p_Val2_23_fu_1001_p3 = ((and_ln318_1_fu_987_p2[0:0] == 1'b1) ? x_l_FH_V_fu_915_p3 : x_l_FH_V_26_fu_970_p2);

assign p_neg168_fu_2175_p3 = ((delta_V_fu_2133_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg169_fu_2372_p3 = ((delta_V_1_fu_2330_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg170_fu_2563_p3 = ((delta_V_2_fu_2523_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg171_fu_2751_p3 = ((delta_V_3_fu_2709_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg172_fu_2948_p3 = ((delta_V_4_fu_2906_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg173_fu_3146_p3 = ((delta_V_5_fu_3106_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg174_fu_3334_p3 = ((delta_V_6_fu_3292_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign res_FH_V_31_fu_3533_p3 = ((and_ln318_24_fu_3527_p2[0:0] == 1'b1) ? res_FH_V_47_fu_3414_p3 : p_Result_73_fu_3493_p4);

assign res_FH_V_33_fu_993_p3 = ((and_ln318_1_fu_987_p2[0:0] == 1'b1) ? 17'd0 : 17'd65536);

assign res_FH_V_34_fu_1134_p3 = ((and_ln318_2_fu_1128_p2[0:0] == 1'b1) ? res_FH_V_33_fu_993_p3 : p_Result_58_fu_1106_p4);

assign res_FH_V_35_fu_1359_p3 = ((and_ln318_3_reg_3687[0:0] == 1'b1) ? res_FH_V_34_reg_3681 : p_Result_59_fu_1350_p4);

assign res_FH_V_36_fu_1461_p3 = ((and_ln318_4_fu_1455_p2[0:0] == 1'b1) ? res_FH_V_35_fu_1359_p3 : p_Result_60_fu_1434_p4);

assign res_FH_V_37_fu_1585_p3 = ((and_ln318_5_fu_1579_p2[0:0] == 1'b1) ? res_FH_V_36_fu_1461_p3 : p_Result_61_fu_1557_p4);

assign res_FH_V_38_fu_1702_p3 = ((and_ln318_6_fu_1696_p2[0:0] == 1'b1) ? res_FH_V_37_reg_3758 : p_Result_62_fu_1676_p4);

assign res_FH_V_39_fu_1825_p3 = ((and_ln318_7_fu_1819_p2[0:0] == 1'b1) ? res_FH_V_38_fu_1702_p3 : p_Result_63_fu_1797_p4);

assign res_FH_V_40_fu_2060_p3 = ((or_ln318_16_fu_2054_p2[0:0] == 1'b1) ? p_Result_65_fu_2044_p4 : res_FH_V_fu_1966_p3);

assign res_FH_V_41_fu_2255_p3 = ((and_ln318_10_fu_2249_p2[0:0] == 1'b1) ? res_FH_V_40_fu_2060_p3 : p_Result_66_fu_2215_p4);

assign res_FH_V_42_fu_2475_p3 = ((and_ln318_12_reg_3828[0:0] == 1'b1) ? res_FH_V_41_reg_3822 : p_Result_67_fu_2466_p4);

assign res_FH_V_43_fu_2637_p3 = ((and_ln318_14_fu_2631_p2[0:0] == 1'b1) ? res_FH_V_42_fu_2475_p3 : p_Result_68_fu_2599_p4);

assign res_FH_V_44_fu_2831_p3 = ((and_ln318_16_fu_2825_p2[0:0] == 1'b1) ? res_FH_V_43_fu_2637_p3 : p_Result_69_fu_2791_p4);

assign res_FH_V_45_fu_3058_p3 = ((and_ln318_18_reg_3863[0:0] == 1'b1) ? res_FH_V_44_reg_3857 : p_Result_70_fu_3049_p4);

assign res_FH_V_46_fu_3220_p3 = ((and_ln318_20_fu_3214_p2[0:0] == 1'b1) ? res_FH_V_45_fu_3058_p3 : p_Result_71_fu_3182_p4);

assign res_FH_V_47_fu_3414_p3 = ((and_ln318_22_fu_3408_p2[0:0] == 1'b1) ? res_FH_V_46_fu_3220_p3 : p_Result_72_fu_3374_p4);

assign res_FH_V_48_fu_3551_p2 = (res_FH_V_31_fu_3533_p3 + 17'd1);

assign res_FH_V_fu_1966_p3 = ((and_ln318_8_reg_3800[0:0] == 1'b1) ? res_FH_V_39_reg_3794 : p_Result_64_fu_1957_p4);

assign res_FH_l_V_fu_3545_p2 = (zext_ln703_fu_3541_p1 + 18'd1);

assign res_I_V_14_fu_3565_p2 = (res_I_V_reg_3666_pp0_iter6_reg + 8'd1);

assign res_I_V_16_fu_352_p3 = ((icmp_ln489_fu_320_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign res_I_V_17_fu_434_p3 = ((icmp_ln489_1_fu_392_p2[0:0] == 1'b1) ? res_I_V_16_fu_352_p3 : p_Result_45_fu_416_p4);

assign res_I_V_18_fu_516_p3 = ((icmp_ln489_2_fu_474_p2[0:0] == 1'b1) ? res_I_V_17_fu_434_p3 : p_Result_47_fu_498_p4);

assign res_I_V_19_fu_609_p3 = ((icmp_ln489_3_reg_3625[0:0] == 1'b1) ? res_I_V_18_reg_3619 : p_Result_49_fu_594_p4);

assign res_I_V_20_fu_689_p3 = ((icmp_ln489_4_fu_647_p2[0:0] == 1'b1) ? res_I_V_19_fu_609_p3 : p_Result_51_fu_671_p4);

assign res_I_V_21_fu_771_p3 = ((icmp_ln489_5_fu_729_p2[0:0] == 1'b1) ? res_I_V_20_fu_689_p3 : p_Result_53_fu_753_p4);

assign res_I_V_22_fu_853_p3 = ((icmp_ln489_6_fu_811_p2[0:0] == 1'b1) ? res_I_V_21_fu_771_p3 : p_Result_55_fu_835_p4);

assign res_I_V_23_fu_3570_p3 = ((p_Result_40_fu_3557_p3[0:0] == 1'b1) ? res_I_V_14_fu_3565_p2 : res_I_V_reg_3666_pp0_iter6_reg);

assign res_I_V_fu_931_p3 = ((icmp_ln489_7_reg_3648[0:0] == 1'b1) ? res_I_V_22_reg_3642 : p_Result_57_fu_922_p4);

assign select_ln99_fu_3595_p3 = ((p_Result_s_fu_3042_p3[0:0] == 1'b1) ? 24'd0 : trunc_ln4_fu_3587_p3);

assign sext_ln640_fu_316_p1 = tmp_fu_306_p4;

assign sub_ln248_1_fu_480_p2 = (p_Result_5_fu_460_p4 - zext_ln489_1_fu_470_p1);

assign sub_ln248_2_fu_562_p2 = (p_Result_9_fu_542_p4 - zext_ln489_2_fu_552_p1);

assign sub_ln248_3_fu_653_p2 = (p_Result_11_fu_633_p4 - zext_ln489_3_fu_643_p1);

assign sub_ln248_4_fu_735_p2 = (p_Result_14_fu_715_p4 - zext_ln489_4_fu_725_p1);

assign sub_ln248_5_fu_817_p2 = (p_Result_17_fu_797_p4 - zext_ln489_5_fu_807_p1);

assign sub_ln248_6_fu_883_p2 = (trunc_ln640_fu_869_p1 - zext_ln489_6_fu_873_p1);

assign sub_ln248_fu_398_p2 = (p_Result_1_fu_378_p4 - zext_ln489_fu_388_p1);

assign sub_ln703_12_fu_2970_p2 = (p_neg172_fu_2948_p3 - mul_FH_V_12_fu_2883_p4);

assign sub_ln703_15_fu_3166_p2 = (p_neg173_fu_3146_p3 - mul_FH_V_13_fu_3084_p4);

assign sub_ln703_18_fu_3356_p2 = (p_neg174_fu_3334_p3 - mul_FH_V_14_fu_3269_p4);

assign sub_ln703_3_fu_2394_p2 = (p_neg169_fu_2372_p3 - mul_FH_V_9_fu_2307_p4);

assign sub_ln703_6_fu_2583_p2 = (p_neg170_fu_2563_p3 - mul_FH_V_10_fu_2501_p4);

assign sub_ln703_9_fu_2773_p2 = (p_neg171_fu_2751_p3 - mul_FH_V_11_fu_2686_p4);

assign sub_ln703_fu_2197_p2 = (p_neg168_fu_2175_p3 - mul_FH_V_8_fu_2110_p4);

assign tmp_10_fu_2666_p4 = {{res_FH_V_43_fu_2637_p3[11:4]}};

assign tmp_11_fu_2863_p4 = {{res_FH_V_44_fu_2831_p3[12:3]}};

assign tmp_12_fu_3064_p4 = {{res_FH_V_45_fu_3058_p3[13:2]}};

assign tmp_13_fu_3249_p4 = {{res_FH_V_46_fu_3220_p3[14:1]}};

assign tmp_14_fu_1040_p4 = {{res_I_V_fu_931_p3[7:1]}};

assign tmp_15_fu_1182_p4 = {{res_I_V_fu_931_p3[7:2]}};

assign tmp_1_fu_370_p3 = {{p_Result_s_38_fu_360_p4}, {1'd1}};

assign tmp_20_fu_2100_p4 = {{res_FH_V_40_fu_2060_p3[16:9]}};

assign tmp_21_fu_2297_p4 = {{res_FH_V_41_fu_2255_p3[16:10]}};

assign tmp_22_fu_2491_p4 = {{res_FH_V_42_fu_2475_p3[16:11]}};

assign tmp_23_fu_2676_p4 = {{res_FH_V_43_fu_2637_p3[16:12]}};

assign tmp_24_fu_2873_p4 = {{res_FH_V_44_fu_2831_p3[16:13]}};

assign tmp_25_fu_3074_p4 = {{res_FH_V_45_fu_3058_p3[16:14]}};

assign tmp_26_fu_3259_p4 = {{res_FH_V_46_fu_3220_p3[16:15]}};

assign tmp_27_fu_3577_p4 = {{res_FH_V_48_fu_3551_p2[16:1]}};

assign tmp_2_fu_452_p3 = {{p_Result_4_fu_442_p4}, {1'd1}};

assign tmp_38_fu_568_p4 = {{x_int_reg[15:14]}};

assign tmp_3_fu_534_p3 = {{p_Result_8_fu_524_p4}, {1'd1}};

assign tmp_4_fu_625_p3 = {{p_Result_10_fu_615_p4}, {1'd1}};

assign tmp_56_fu_3458_p3 = res_FH_V_47_fu_3414_p3[32'd16];

assign tmp_5_fu_707_p3 = {{p_Result_13_fu_697_p4}, {1'd1}};

assign tmp_6_fu_789_p3 = {{p_Result_16_fu_779_p4}, {1'd1}};

assign tmp_7_fu_2287_p4 = {{res_FH_V_41_fu_2255_p3[9:6]}};

assign tmp_8_fu_861_p3 = {{res_I_V_22_fu_853_p3}, {1'd1}};

assign tmp_9_fu_2481_p4 = {{res_FH_V_42_fu_2475_p3[10:5]}};

assign tmp_fu_306_p4 = {{x_int_reg[31:30]}};

assign tmp_s_fu_2090_p4 = {{res_FH_V_40_fu_2060_p3[8:7]}};

assign trunc_ln104_1_fu_1168_p1 = res_I_V_fu_931_p3[1:0];

assign trunc_ln104_2_fu_1282_p1 = res_I_V_fu_931_p3[2:0];

assign trunc_ln104_3_fu_1296_p1 = res_I_V_fu_931_p3[3:0];

assign trunc_ln104_4_fu_1310_p1 = res_I_V_fu_931_p3[4:0];

assign trunc_ln104_5_fu_1324_p1 = res_I_V_fu_931_p3[5:0];

assign trunc_ln104_6_fu_1338_p1 = res_I_V_fu_931_p3[6:0];

assign trunc_ln104_7_fu_3446_p1 = res_FH_V_47_fu_3414_p3[15:0];

assign trunc_ln104_fu_1026_p1 = res_I_V_fu_931_p3[0:0];

assign trunc_ln2_fu_937_p3 = {{9'd0}, {res_I_V_fu_931_p3}};

assign trunc_ln318_1_fu_1050_p3 = {{10'd0}, {tmp_14_fu_1040_p4}};

assign trunc_ln318_2_fu_1192_p3 = {{11'd0}, {tmp_15_fu_1182_p4}};

assign trunc_ln318_3_fu_1384_p3 = {{12'd0}, {tmp_16_reg_3713}};

assign trunc_ln318_4_fu_1502_p3 = {{13'd0}, {tmp_17_reg_3723}};

assign trunc_ln318_5_fu_1640_p3 = {{14'd0}, {tmp_18_reg_3733_pp0_iter3_reg}};

assign trunc_ln318_6_fu_1742_p3 = {{15'd0}, {tmp_19_reg_3743_pp0_iter3_reg}};

assign trunc_ln318_7_fu_1868_p3 = {{16'd0}, {tmp_45_reg_3753_pp0_iter3_reg}};

assign trunc_ln4_fu_3587_p3 = {{res_I_V_23_fu_3570_p3}, {tmp_27_fu_3577_p4}};

assign trunc_ln640_fu_869_p1 = x_l_I_V_78_fu_845_p3[9:0];

assign trunc_ln731_fu_302_p1 = x_int_reg[15:0];

assign trunc_ln_fu_288_p4 = {{x_int_reg[31:16]}};

assign x_l_FH_V_26_fu_970_p2 = ($signed(x_l_FH_V_fu_915_p3) + $signed(17'd98304));

assign x_l_FH_V_27_fu_1100_p2 = (p_Val2_23_fu_1001_p3 - mul_FH_V_fu_1030_p4);

assign x_l_FH_V_28_fu_1142_p3 = ((and_ln318_2_fu_1128_p2[0:0] == 1'b1) ? p_Val2_23_fu_1001_p3 : x_l_FH_V_27_fu_1100_p2);

assign x_l_FH_V_29_fu_1242_p2 = (x_l_FH_V_28_fu_1142_p3 - mul_FH_V_1_fu_1172_p4);

assign x_l_FH_V_30_fu_1266_p3 = ((and_ln318_3_fu_1260_p2[0:0] == 1'b1) ? x_l_FH_V_28_fu_1142_p3 : x_l_FH_V_29_fu_1242_p2);

assign x_l_FH_V_31_fu_1429_p2 = (x_l_FH_V_30_reg_3692 - mul_FH_V_2_fu_1375_p4);

assign x_l_FH_V_32_fu_1469_p3 = ((and_ln318_4_fu_1455_p2[0:0] == 1'b1) ? x_l_FH_V_30_reg_3692 : x_l_FH_V_31_fu_1429_p2);

assign x_l_FH_V_33_fu_1551_p2 = (x_l_FH_V_32_fu_1469_p3 - mul_FH_V_3_fu_1493_p4);

assign x_l_FH_V_34_fu_1593_p3 = ((and_ln318_5_fu_1579_p2[0:0] == 1'b1) ? x_l_FH_V_32_fu_1469_p3 : x_l_FH_V_33_fu_1551_p2);

assign x_l_FH_V_35_fu_1672_p2 = (x_l_FH_V_34_reg_3764 - mul_FH_V_4_reg_3778);

assign x_l_FH_V_36_fu_1709_p3 = ((and_ln318_6_fu_1696_p2[0:0] == 1'b1) ? x_l_FH_V_34_reg_3764 : x_l_FH_V_35_fu_1672_p2);

assign x_l_FH_V_37_fu_1791_p2 = (x_l_FH_V_36_fu_1709_p3 - mul_FH_V_5_fu_1733_p4);

assign x_l_FH_V_38_fu_1833_p3 = ((and_ln318_7_fu_1819_p2[0:0] == 1'b1) ? x_l_FH_V_36_fu_1709_p3 : x_l_FH_V_37_fu_1791_p2);

assign x_l_FH_V_39_fu_1917_p2 = (x_l_FH_V_38_fu_1833_p3 - mul_FH_V_6_fu_1859_p4);

assign x_l_FH_V_40_fu_1941_p3 = ((and_ln318_8_fu_1935_p2[0:0] == 1'b1) ? x_l_FH_V_38_fu_1833_p3 : x_l_FH_V_39_fu_1917_p2);

assign x_l_FH_V_41_fu_2039_p2 = (x_l_FH_V_40_reg_3805 + xor_ln703_fu_2033_p2);

assign x_l_FH_V_42_fu_2076_p3 = ((or_ln318_16_fu_2054_p2[0:0] == 1'b1) ? x_l_FH_V_41_fu_2039_p2 : x_l_FH_V_40_reg_3805);

assign x_l_FH_V_43_fu_2203_p2 = (sub_ln703_fu_2197_p2 + x_l_FH_V_42_fu_2076_p3);

assign x_l_FH_V_44_fu_2271_p3 = ((and_ln318_10_fu_2249_p2[0:0] == 1'b1) ? x_l_FH_V_42_fu_2076_p3 : x_l_FH_V_43_fu_2203_p2);

assign x_l_FH_V_45_fu_2400_p2 = (sub_ln703_3_fu_2394_p2 + x_l_FH_V_44_fu_2271_p3);

assign x_l_FH_V_46_fu_2450_p3 = ((and_ln318_12_fu_2436_p2[0:0] == 1'b1) ? x_l_FH_V_44_fu_2271_p3 : x_l_FH_V_45_fu_2400_p2);

assign x_l_FH_V_47_fu_2589_p2 = (sub_ln703_6_fu_2583_p2 + x_l_FH_V_46_reg_3840);

assign x_l_FH_V_48_fu_2652_p3 = ((and_ln318_14_fu_2631_p2[0:0] == 1'b1) ? x_l_FH_V_46_reg_3840 : x_l_FH_V_47_fu_2589_p2);

assign x_l_FH_V_49_fu_2779_p2 = (sub_ln703_9_fu_2773_p2 + x_l_FH_V_48_fu_2652_p3);

assign x_l_FH_V_50_fu_2847_p3 = ((and_ln318_16_fu_2825_p2[0:0] == 1'b1) ? x_l_FH_V_48_fu_2652_p3 : x_l_FH_V_49_fu_2779_p2);

assign x_l_FH_V_51_fu_2976_p2 = (sub_ln703_12_fu_2970_p2 + x_l_FH_V_50_fu_2847_p3);

assign x_l_FH_V_52_fu_3026_p3 = ((and_ln318_18_fu_3012_p2[0:0] == 1'b1) ? x_l_FH_V_50_fu_2847_p3 : x_l_FH_V_51_fu_2976_p2);

assign x_l_FH_V_53_fu_3172_p2 = (sub_ln703_15_fu_3166_p2 + x_l_FH_V_52_reg_3875);

assign x_l_FH_V_54_fu_3235_p3 = ((and_ln318_20_fu_3214_p2[0:0] == 1'b1) ? x_l_FH_V_52_reg_3875 : x_l_FH_V_53_fu_3172_p2);

assign x_l_FH_V_55_fu_3362_p2 = (sub_ln703_18_fu_3356_p2 + x_l_FH_V_54_fu_3235_p3);

assign x_l_FH_V_56_fu_3430_p3 = ((and_ln318_22_fu_3408_p2[0:0] == 1'b1) ? x_l_FH_V_54_fu_3235_p3 : x_l_FH_V_55_fu_3362_p2);

assign x_l_FH_V_fu_915_p3 = {{trunc_ln731_reg_3608_pp0_iter1_reg}, {1'd0}};

assign x_l_FL_V_11_fu_3177_p2 = (x_l_FL_V_20_reg_3868 - mul_FL_V_5_fu_3093_p3);

assign x_l_FL_V_13_fu_3368_p2 = (x_l_FL_V_21_fu_3228_p3 - mul_FL_V_6_fu_3278_p3);

assign x_l_FL_V_14_fu_3422_p3 = ((and_ln318_22_fu_3408_p2[0:0] == 1'b1) ? x_l_FL_V_21_fu_3228_p3 : x_l_FL_V_13_fu_3368_p2);

assign x_l_FL_V_15_fu_2068_p3 = ((or_ln318_16_fu_2054_p2[0:0] == 1'b1) ? 17'd65536 : 17'd0);

assign x_l_FL_V_16_fu_2263_p3 = ((and_ln318_10_fu_2249_p2[0:0] == 1'b1) ? x_l_FL_V_15_fu_2068_p3 : x_l_FL_V_fu_2209_p2);

assign x_l_FL_V_17_fu_2442_p3 = ((and_ln318_12_fu_2436_p2[0:0] == 1'b1) ? x_l_FL_V_16_fu_2263_p3 : x_l_FL_V_3_fu_2406_p2);

assign x_l_FL_V_18_fu_2645_p3 = ((and_ln318_14_fu_2631_p2[0:0] == 1'b1) ? x_l_FL_V_17_reg_3833 : x_l_FL_V_5_fu_2594_p2);

assign x_l_FL_V_19_fu_2839_p3 = ((and_ln318_16_fu_2825_p2[0:0] == 1'b1) ? x_l_FL_V_18_fu_2645_p3 : x_l_FL_V_7_fu_2785_p2);

assign x_l_FL_V_20_fu_3018_p3 = ((and_ln318_18_fu_3012_p2[0:0] == 1'b1) ? x_l_FL_V_19_fu_2839_p3 : x_l_FL_V_9_fu_2982_p2);

assign x_l_FL_V_21_fu_3228_p3 = ((and_ln318_20_fu_3214_p2[0:0] == 1'b1) ? x_l_FL_V_20_reg_3868 : x_l_FL_V_11_fu_3177_p2);

assign x_l_FL_V_3_fu_2406_p2 = (x_l_FL_V_16_fu_2263_p3 - mul_FL_V_1_fu_2316_p3);

assign x_l_FL_V_5_fu_2594_p2 = (x_l_FL_V_17_reg_3833 - mul_FL_V_2_fu_2510_p3);

assign x_l_FL_V_7_fu_2785_p2 = (x_l_FL_V_18_fu_2645_p3 - mul_FL_V_3_fu_2695_p3);

assign x_l_FL_V_9_fu_2982_p2 = (x_l_FL_V_19_fu_2839_p3 - mul_FL_V_4_fu_2892_p3);

assign x_l_FL_V_fu_2209_p2 = (x_l_FL_V_15_fu_2068_p3 - mul_FL_V_fu_2119_p3);

assign x_l_I_V_100_fu_2386_p3 = ((and_ln331_1_fu_2366_p2[0:0] == 1'b1) ? x_l_I_V_99_fu_2279_p3 : x_l_I_V_54_fu_2380_p2);

assign x_l_I_V_101_fu_2458_p3 = ((and_ln318_12_fu_2436_p2[0:0] == 1'b1) ? x_l_I_V_99_fu_2279_p3 : x_l_I_V_100_fu_2386_p3);

assign x_l_I_V_102_fu_2576_p3 = ((and_ln331_2_fu_2557_p2[0:0] == 1'b1) ? x_l_I_V_101_reg_3849 : x_l_I_V_57_fu_2571_p2);

assign x_l_I_V_103_fu_2659_p3 = ((and_ln318_14_fu_2631_p2[0:0] == 1'b1) ? x_l_I_V_101_reg_3849 : x_l_I_V_102_fu_2576_p3);

assign x_l_I_V_104_fu_2765_p3 = ((and_ln331_3_fu_2745_p2[0:0] == 1'b1) ? x_l_I_V_103_fu_2659_p3 : x_l_I_V_60_fu_2759_p2);

assign x_l_I_V_105_fu_2855_p3 = ((and_ln318_16_fu_2825_p2[0:0] == 1'b1) ? x_l_I_V_103_fu_2659_p3 : x_l_I_V_104_fu_2765_p3);

assign x_l_I_V_106_fu_2962_p3 = ((and_ln331_4_fu_2942_p2[0:0] == 1'b1) ? x_l_I_V_105_fu_2855_p3 : x_l_I_V_63_fu_2956_p2);

assign x_l_I_V_107_fu_3034_p3 = ((and_ln318_18_fu_3012_p2[0:0] == 1'b1) ? x_l_I_V_105_fu_2855_p3 : x_l_I_V_106_fu_2962_p3);

assign x_l_I_V_108_fu_3159_p3 = ((and_ln331_5_fu_3140_p2[0:0] == 1'b1) ? x_l_I_V_107_reg_3884 : x_l_I_V_66_fu_3154_p2);

assign x_l_I_V_109_fu_3242_p3 = ((and_ln318_20_fu_3214_p2[0:0] == 1'b1) ? x_l_I_V_107_reg_3884 : x_l_I_V_108_fu_3159_p3);

assign x_l_I_V_110_fu_3348_p3 = ((and_ln331_6_fu_3328_p2[0:0] == 1'b1) ? x_l_I_V_109_fu_3242_p3 : x_l_I_V_69_fu_3342_p2);

assign x_l_I_V_111_fu_3438_p3 = ((and_ln318_22_fu_3408_p2[0:0] == 1'b1) ? x_l_I_V_109_fu_3242_p3 : x_l_I_V_110_fu_3348_p3);

assign x_l_I_V_17_fu_909_p2 = ($signed(x_l_I_V_79_fu_901_p3) + $signed(19'd524287));

assign x_l_I_V_18_fu_959_p3 = ((icmp_ln318_1_reg_3636_pp0_iter1_reg[0:0] == 1'b1) ? x_l_I_V_17_reg_3661 : x_l_I_V_79_reg_3653);

assign x_l_I_V_21_fu_1086_p3 = ((icmp_ln318_3_fu_1068_p2[0:0] == 1'b1) ? x_l_I_V_fu_1080_p2 : x_l_I_V_81_fu_1009_p3);

assign x_l_I_V_24_fu_1222_p2 = ($signed(x_l_I_V_83_fu_1150_p3) + $signed(19'd524287));

assign x_l_I_V_25_fu_1228_p3 = ((icmp_ln318_5_fu_1210_p2[0:0] == 1'b1) ? x_l_I_V_24_fu_1222_p2 : x_l_I_V_83_fu_1150_p3);

assign x_l_I_V_28_fu_1411_p2 = ($signed(x_l_I_V_85_reg_3699) + $signed(19'd524287));

assign x_l_I_V_29_fu_1416_p3 = ((icmp_ln318_7_fu_1400_p2[0:0] == 1'b1) ? x_l_I_V_28_fu_1411_p2 : x_l_I_V_85_reg_3699);

assign x_l_I_V_32_fu_1531_p2 = ($signed(x_l_I_V_87_fu_1476_p3) + $signed(19'd524287));

assign x_l_I_V_33_fu_1537_p3 = ((icmp_ln318_17_fu_1519_p2[0:0] == 1'b1) ? x_l_I_V_32_fu_1531_p2 : x_l_I_V_87_fu_1476_p3);

assign x_l_I_V_36_fu_1634_p2 = ($signed(x_l_I_V_89_fu_1601_p3) + $signed(19'd524287));

assign x_l_I_V_37_fu_1661_p3 = ((icmp_ln318_19_reg_3783[0:0] == 1'b1) ? x_l_I_V_36_reg_3789 : x_l_I_V_89_reg_3770);

assign x_l_I_V_40_fu_1771_p2 = ($signed(x_l_I_V_91_fu_1716_p3) + $signed(19'd524287));

assign x_l_I_V_41_fu_1777_p3 = ((icmp_ln318_21_fu_1759_p2[0:0] == 1'b1) ? x_l_I_V_40_fu_1771_p2 : x_l_I_V_91_fu_1716_p3);

assign x_l_I_V_44_fu_1897_p2 = ($signed(x_l_I_V_93_fu_1841_p3) + $signed(19'd524287));

assign x_l_I_V_45_fu_1903_p3 = ((icmp_ln318_23_fu_1885_p2[0:0] == 1'b1) ? x_l_I_V_44_fu_1897_p2 : x_l_I_V_93_fu_1841_p3);

assign x_l_I_V_48_fu_2021_p2 = ($signed(x_l_I_V_95_reg_3813) + $signed(19'd524287));

assign x_l_I_V_51_fu_2183_p2 = ($signed(x_l_I_V_97_fu_2083_p3) + $signed(19'd524287));

assign x_l_I_V_54_fu_2380_p2 = ($signed(x_l_I_V_99_fu_2279_p3) + $signed(19'd524287));

assign x_l_I_V_57_fu_2571_p2 = ($signed(x_l_I_V_101_reg_3849) + $signed(19'd524287));

assign x_l_I_V_60_fu_2759_p2 = ($signed(x_l_I_V_103_fu_2659_p3) + $signed(19'd524287));

assign x_l_I_V_63_fu_2956_p2 = ($signed(x_l_I_V_105_fu_2855_p3) + $signed(19'd524287));

assign x_l_I_V_66_fu_3154_p2 = ($signed(x_l_I_V_107_reg_3884) + $signed(19'd524287));

assign x_l_I_V_69_fu_3342_p2 = ($signed(x_l_I_V_109_fu_3242_p3) + $signed(19'd524287));

assign x_l_I_V_72_fu_344_p3 = ((icmp_ln489_fu_320_p2[0:0] == 1'b1) ? zext_ln708_fu_298_p1 : p_Result_43_fu_332_p5);

assign x_l_I_V_73_fu_426_p3 = ((icmp_ln489_1_fu_392_p2[0:0] == 1'b1) ? x_l_I_V_72_fu_344_p3 : p_Result_44_fu_404_p5);

assign x_l_I_V_74_fu_508_p3 = ((icmp_ln489_2_fu_474_p2[0:0] == 1'b1) ? x_l_I_V_73_fu_426_p3 : p_Result_46_fu_486_p5);

assign x_l_I_V_75_fu_603_p3 = ((icmp_ln489_3_reg_3625[0:0] == 1'b1) ? x_l_I_V_74_reg_3613 : p_Result_48_fu_584_p5);

assign x_l_I_V_76_fu_681_p3 = ((icmp_ln489_4_fu_647_p2[0:0] == 1'b1) ? x_l_I_V_75_fu_603_p3 : p_Result_50_fu_659_p5);

assign x_l_I_V_77_fu_763_p3 = ((icmp_ln489_5_fu_729_p2[0:0] == 1'b1) ? x_l_I_V_76_fu_681_p3 : p_Result_52_fu_741_p5);

assign x_l_I_V_78_fu_845_p3 = ((icmp_ln489_6_fu_811_p2[0:0] == 1'b1) ? x_l_I_V_77_fu_763_p3 : p_Result_54_fu_823_p5);

assign x_l_I_V_79_fu_901_p3 = ((icmp_ln489_7_fu_877_p2[0:0] == 1'b1) ? x_l_I_V_78_fu_845_p3 : p_Result_56_fu_889_p5);

assign x_l_I_V_80_fu_964_p2 = (x_l_I_V_18_fu_959_p3 - zext_ln318_fu_945_p1);

assign x_l_I_V_81_fu_1009_p3 = ((and_ln318_1_fu_987_p2[0:0] == 1'b1) ? x_l_I_V_79_reg_3653 : x_l_I_V_80_fu_964_p2);

assign x_l_I_V_82_fu_1094_p2 = (x_l_I_V_21_fu_1086_p3 - zext_ln318_1_fu_1058_p1);

assign x_l_I_V_83_fu_1150_p3 = ((and_ln318_2_fu_1128_p2[0:0] == 1'b1) ? x_l_I_V_81_fu_1009_p3 : x_l_I_V_82_fu_1094_p2);

assign x_l_I_V_84_fu_1236_p2 = (x_l_I_V_25_fu_1228_p3 - zext_ln318_2_fu_1200_p1);

assign x_l_I_V_85_fu_1274_p3 = ((and_ln318_3_fu_1260_p2[0:0] == 1'b1) ? x_l_I_V_83_fu_1150_p3 : x_l_I_V_84_fu_1236_p2);

assign x_l_I_V_86_fu_1423_p2 = (x_l_I_V_29_fu_1416_p3 - zext_ln318_3_fu_1391_p1);

assign x_l_I_V_87_fu_1476_p3 = ((and_ln318_4_fu_1455_p2[0:0] == 1'b1) ? x_l_I_V_85_reg_3699 : x_l_I_V_86_fu_1423_p2);

assign x_l_I_V_88_fu_1545_p2 = (x_l_I_V_33_fu_1537_p3 - zext_ln318_4_fu_1509_p1);

assign x_l_I_V_89_fu_1601_p3 = ((and_ln318_5_fu_1579_p2[0:0] == 1'b1) ? x_l_I_V_87_fu_1476_p3 : x_l_I_V_88_fu_1545_p2);

assign x_l_I_V_90_fu_1666_p2 = (x_l_I_V_37_fu_1661_p3 - zext_ln318_5_fu_1647_p1);

assign x_l_I_V_91_fu_1716_p3 = ((and_ln318_6_fu_1696_p2[0:0] == 1'b1) ? x_l_I_V_89_reg_3770 : x_l_I_V_90_fu_1666_p2);

assign x_l_I_V_92_fu_1785_p2 = (x_l_I_V_41_fu_1777_p3 - zext_ln318_6_fu_1749_p1);

assign x_l_I_V_93_fu_1841_p3 = ((and_ln318_7_fu_1819_p2[0:0] == 1'b1) ? x_l_I_V_91_fu_1716_p3 : x_l_I_V_92_fu_1785_p2);

assign x_l_I_V_94_fu_1911_p2 = (x_l_I_V_45_fu_1903_p3 - zext_ln318_7_fu_1875_p1);

assign x_l_I_V_95_fu_1949_p3 = ((and_ln318_8_fu_1935_p2[0:0] == 1'b1) ? x_l_I_V_93_fu_1841_p3 : x_l_I_V_94_fu_1911_p2);

assign x_l_I_V_96_fu_2026_p3 = ((xor_ln331_7_fu_2015_p2[0:0] == 1'b1) ? x_l_I_V_48_fu_2021_p2 : x_l_I_V_95_reg_3813);

assign x_l_I_V_97_fu_2083_p3 = ((or_ln318_16_fu_2054_p2[0:0] == 1'b1) ? x_l_I_V_96_fu_2026_p3 : x_l_I_V_95_reg_3813);

assign x_l_I_V_98_fu_2189_p3 = ((and_ln331_fu_2169_p2[0:0] == 1'b1) ? x_l_I_V_97_fu_2083_p3 : x_l_I_V_51_fu_2183_p2);

assign x_l_I_V_99_fu_2279_p3 = ((and_ln318_10_fu_2249_p2[0:0] == 1'b1) ? x_l_I_V_97_fu_2083_p3 : x_l_I_V_98_fu_2189_p3);

assign x_l_I_V_fu_1080_p2 = ($signed(x_l_I_V_81_fu_1009_p3) + $signed(19'd524287));

assign xor_ln1494_10_fu_2619_p2 = (icmp_ln1494_12_fu_2614_p2 ^ 1'd1);

assign xor_ln1494_11_fu_2813_p2 = (icmp_ln1494_13_fu_2807_p2 ^ 1'd1);

assign xor_ln1494_12_fu_3000_p2 = (icmp_ln1494_14_fu_2994_p2 ^ 1'd1);

assign xor_ln1494_13_fu_3202_p2 = (icmp_ln1494_15_fu_3197_p2 ^ 1'd1);

assign xor_ln1494_14_fu_3396_p2 = (icmp_ln1494_16_fu_3390_p2 ^ 1'd1);

assign xor_ln1494_15_fu_3515_p2 = (icmp_ln1494_17_fu_3509_p2 ^ 1'd1);

assign xor_ln1494_1_fu_1122_p2 = (icmp_ln1494_1_fu_1116_p2 ^ 1'd1);

assign xor_ln1494_2_fu_1254_p2 = (icmp_ln1494_2_fu_1248_p2 ^ 1'd1);

assign xor_ln1494_3_fu_1449_p2 = (icmp_ln1494_3_fu_1444_p2 ^ 1'd1);

assign xor_ln1494_4_fu_1573_p2 = (icmp_ln1494_4_fu_1567_p2 ^ 1'd1);

assign xor_ln1494_5_fu_1690_p2 = (icmp_ln1494_5_fu_1685_p2 ^ 1'd1);

assign xor_ln1494_6_fu_1813_p2 = (icmp_ln1494_6_fu_1807_p2 ^ 1'd1);

assign xor_ln1494_7_fu_1929_p2 = (icmp_ln1494_7_fu_1923_p2 ^ 1'd1);

assign xor_ln1494_8_fu_2237_p2 = (icmp_ln1494_10_fu_2231_p2 ^ 1'd1);

assign xor_ln1494_9_fu_2424_p2 = (icmp_ln1494_11_fu_2418_p2 ^ 1'd1);

assign xor_ln1494_fu_981_p2 = (icmp_ln1494_fu_976_p2 ^ 1'd1);

assign xor_ln1495_1_fu_2360_p2 = (icmp_ln1495_1_fu_2354_p2 ^ 1'd1);

assign xor_ln1495_2_fu_2551_p2 = (icmp_ln1495_2_fu_2546_p2 ^ 1'd1);

assign xor_ln1495_3_fu_2739_p2 = (icmp_ln1495_3_fu_2733_p2 ^ 1'd1);

assign xor_ln1495_4_fu_2936_p2 = (icmp_ln1495_4_fu_2930_p2 ^ 1'd1);

assign xor_ln1495_5_fu_3134_p2 = (icmp_ln1495_5_fu_3129_p2 ^ 1'd1);

assign xor_ln1495_6_fu_3322_p2 = (icmp_ln1495_6_fu_3316_p2 ^ 1'd1);

assign xor_ln1495_fu_2163_p2 = (icmp_ln1495_fu_2157_p2 ^ 1'd1);

assign xor_ln331_1_fu_2342_p2 = (delta_V_1_fu_2330_p2 ^ 1'd1);

assign xor_ln331_2_fu_2534_p2 = (delta_V_2_fu_2523_p2 ^ 1'd1);

assign xor_ln331_3_fu_2721_p2 = (delta_V_3_fu_2709_p2 ^ 1'd1);

assign xor_ln331_4_fu_2918_p2 = (delta_V_4_fu_2906_p2 ^ 1'd1);

assign xor_ln331_5_fu_3117_p2 = (delta_V_5_fu_3106_p2 ^ 1'd1);

assign xor_ln331_6_fu_3304_p2 = (delta_V_6_fu_3292_p2 ^ 1'd1);

assign xor_ln331_7_fu_2015_p2 = (icmp_ln331_fu_2010_p2 ^ 1'd1);

assign xor_ln331_fu_2145_p2 = (delta_V_fu_2133_p2 ^ 1'd1);

assign xor_ln703_fu_2033_p2 = (mul_FH_V_7_fu_1982_p3 ^ 17'd131071);

assign zext_ln318_1_fu_1058_p1 = trunc_ln318_1_fu_1050_p3;

assign zext_ln318_2_fu_1200_p1 = trunc_ln318_2_fu_1192_p3;

assign zext_ln318_3_fu_1391_p1 = trunc_ln318_3_fu_1384_p3;

assign zext_ln318_4_fu_1509_p1 = trunc_ln318_4_fu_1502_p3;

assign zext_ln318_5_fu_1647_p1 = trunc_ln318_5_fu_1640_p3;

assign zext_ln318_6_fu_1749_p1 = trunc_ln318_6_fu_1742_p3;

assign zext_ln318_7_fu_1875_p1 = trunc_ln318_7_fu_1868_p3;

assign zext_ln318_fu_945_p1 = trunc_ln2_fu_937_p3;

assign zext_ln489_1_fu_470_p1 = tmp_2_fu_452_p3;

assign zext_ln489_2_fu_552_p1 = tmp_3_fu_534_p3;

assign zext_ln489_3_fu_643_p1 = tmp_4_fu_625_p3;

assign zext_ln489_4_fu_725_p1 = tmp_5_fu_707_p3;

assign zext_ln489_5_fu_807_p1 = tmp_6_fu_789_p3;

assign zext_ln489_6_fu_873_p1 = tmp_8_fu_861_p3;

assign zext_ln489_fu_388_p1 = tmp_1_fu_370_p3;

assign zext_ln703_fu_3541_p1 = res_FH_V_31_fu_3533_p3;

assign zext_ln708_fu_298_p1 = trunc_ln_fu_288_p4;

always @ (posedge ap_clk) begin
    x_l_FH_V_30_reg_3692[0] <= 1'b0;
    x_l_FH_V_34_reg_3764[0] <= 1'b0;
    mul_FH_V_4_reg_3778[5:0] <= 6'b100000;
    x_l_FH_V_40_reg_3805[0] <= 1'b0;
    x_l_FL_V_17_reg_3833[11:0] <= 12'b000000000000;
    x_l_FL_V_20_reg_3868[5:0] <= 6'b000000;
end

endmodule //sqrt_fix_sqrt_fixed_32_16_s
