set rtl_all {
simd_src/SIMD_instruction_decoder.v \
simd_src/simd_ld_st_interface.v \
simd_src/simd_data_shuffler.v \
simd_src/saturate.v \
simd_src/pipeline.v \
simd_src/nested_loop.v \
simd_src/namespace_mux.v \
simd_src/mul_unit.v \
simd_src/mem_walker_stride_group_simd.v \
simd_src/iterator_memories_flexible_ns.v \
simd_src/iterator_address_gen_new.v \
simd_src/execute_control_pipelines.v \
simd_src/datatype_cast.v \
simd_src/controller_fsm_group_simd.v \
simd_src/compute_unit.v \
simd_src/comparison_unit.v \
simd_src/calculus_unit.v \
simd_src/arithmetic_unit.v \
simd_src/SIMD_top.v \
genesys_src/register_sync.v \
genesys_src/obuf_wrapper.v \
genesys_src/obuf.v \
genesys_src/mem_walker_stride_group.v \
genesys_src/ibuf.v \
genesys_src/ddr_memory_interface_control_m_axi.sv \
genesys_src/control_m_axi_write_master.sv \
genesys_src/control_m_axi_read_master.sv \
genesys_src/controller_fsm_group.v \
genesys_src/bias_buffer.v \
genesys_src/mem_request_splitter.sv \
genesys_src/control_m_axi_write_master_fifo.sv \
genesys_src/ddr_memory_interface_control_m_axi_fifo.sv \
genesys_src/control_m_axi_write_master_counter.sv \
genesys_src/control_m_axi_read_master_fifo.sv \
genesys_src/systolic_fpga_control_s_axi.v \
genesys_src/pe.v \
genesys_src/signed_adder.v \
genesys_src/instruction_memory.v \
genesys_src/instruction_memory_wrapper.v \
genesys_src/ibuf_interface.v \
genesys_src/compute_addr_gen.v \
genesys_src/controller.sv \
genesys_src/obuf_interface.v \
genesys_src/systolic_array.v \
genesys_src/truncator.v \
genesys_src/macc.v \
genesys_src/decoder.v \
genesys_src/tag_logic.v \
genesys_src/tag_sync.v \
genesys_src/parambuf_interface.v \
genesys_src/base_addr_gen.v \
genesys_src/genesys_top_module.v \
}  

